/*
 * Responses Test
 *
 * This specification is intended for testing purposes. It demonstrates various response media types.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApplicationJsonObjectResponse200Response struct {
	Status string `json:"status,omitempty"`

	Value int64 `json:"value,omitempty"`
}
