/**
 * OpenAPI Petstore
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIPetApi_H
#define OAI_OAIPetApi_H

#include "OAIBaseApi.h"
#include <QtNetwork/qrestreply.h>

#include "OAIApiResponse.h"
#include "OAIHttpFileElement.h"
#include "OAIPet.h"
#include <QString>

namespace OpenAPI {

class OAIPetApi : public OAIBaseApi {
    Q_OBJECT
public:
    OAIPetApi(QObject *parent = nullptr);
    virtual ~OAIPetApi();

    void initializeServerConfigs();
public:
    /**
    * \internal
    * The auto-generated API:
    * void addPet(const OAIPet &oAIPet);
    * void addPet(const OAIPet &oAIPet, QObject *object, [&](QRestReply &reply, OAIPet &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(addPet, (const OAIPet &oAIPet), (oAIPet), (OAIPet), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void deletePet(const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &apiKey);
    * void deletePet(const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &apiKey, QObject *object, [&](QRestReply &reply){});
    * \endinternal
    */
    OAI_ADD_OPERATION_WITH_NO_RESPONSE_IMPL(deletePet, (const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &apiKey = ::OpenAPI::OptionalParam<QString>()), (petId, apiKey), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsByAgeAndPatience(const QList<qint32> &petData);
    * void findPetsByAgeAndPatience(const QList<qint32> &petData, QObject *object, [&](QRestReply &reply, QList<OAIPet> &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(findPetsByAgeAndPatience, (const QList<qint32> &petData), (petData), (QList<OAIPet>), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsByStatus(const QList<QString> &status);
    * void findPetsByStatus(const QList<QString> &status, QObject *object, [&](QRestReply &reply, QList<OAIPet> &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(findPetsByStatus, (const QList<QString> &status), (status), (QList<OAIPet>), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsByTags(const QList<QString> &tags);
    * void findPetsByTags(const QList<QString> &tags, QObject *object, [&](QRestReply &reply, QList<OAIPet> &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(findPetsByTags, (const QList<QString> &tags), (tags), (QList<OAIPet>), Q_DECL_DEPRECATED)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsImageById(const qint64 &petId);
    * void findPetsImageById(const qint64 &petId, QObject *object, [&](QRestReply &reply, QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(findPetsImageById, (const qint64 &petId), (petId), (QString), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void getJsonFile(const qint64 &petId);
    * void getJsonFile(const qint64 &petId, QObject *object, [&](QRestReply &reply, OAIHttpFileElement &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(getJsonFile, (const qint64 &petId), (petId), (OAIHttpFileElement), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void getPetById(const qint64 &petId);
    * void getPetById(const qint64 &petId, QObject *object, [&](QRestReply &reply, OAIPet &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(getPetById, (const qint64 &petId), (petId), (OAIPet), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void updatePet(const OAIPet &oAIPet);
    * void updatePet(const OAIPet &oAIPet, QObject *object, [&](QRestReply &reply, OAIPet &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(updatePet, (const OAIPet &oAIPet), (oAIPet), (OAIPet), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void updatePetWithForm(const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &name, const ::OpenAPI::OptionalParam<QString> &status);
    * void updatePetWithForm(const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &name, const ::OpenAPI::OptionalParam<QString> &status, QObject *object, [&](QRestReply &reply){});
    * \endinternal
    */
    OAI_ADD_OPERATION_WITH_NO_RESPONSE_IMPL(updatePetWithForm, (const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &name = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &status = ::OpenAPI::OptionalParam<QString>()), (petId, name, status), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void uploadFile(const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &additionalMetadata, const ::OpenAPI::OptionalParam<OAIHttpFileElement> &file);
    * void uploadFile(const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &additionalMetadata, const ::OpenAPI::OptionalParam<OAIHttpFileElement> &file, QObject *object, [&](QRestReply &reply, OAIApiResponse &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(uploadFile, (const qint64 &petId, const ::OpenAPI::OptionalParam<QString> &additionalMetadata = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<OAIHttpFileElement> &file = ::OpenAPI::OptionalParam<OAIHttpFileElement>()), (petId, additionalMetadata, file), (OAIApiResponse), /* non-deprecated */)

Q_SIGNALS:
    /** Signal is emitted, if addPet() request completed successfully. The \a summary contains a serialized server response. */
    void addPetFinished(OAIPet summary);
    /** Signal is emitted, if addPet() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void addPetErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if deletePet() request completed successfully. */
    void deletePetFinished();
    /** Signal is emitted, if deletePet() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void deletePetErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsByAgeAndPatience() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsByAgeAndPatienceFinished(QList<OAIPet> summary);
    /** Signal is emitted, if findPetsByAgeAndPatience() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsByAgeAndPatienceErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsByStatus() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsByStatusFinished(QList<OAIPet> summary);
    /** Signal is emitted, if findPetsByStatus() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsByStatusErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsByTags() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsByTagsFinished(QList<OAIPet> summary);
    /** Signal is emitted, if findPetsByTags() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsByTagsErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsImageById() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsImageByIdFinished(QString summary);
    /** Signal is emitted, if findPetsImageById() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsImageByIdErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if getJsonFile() request completed successfully. The \a summary contains a serialized server response. */
    void getJsonFileFinished(OAIHttpFileElement summary);
    /** Signal is emitted, if getJsonFile() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void getJsonFileErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if getPetById() request completed successfully. The \a summary contains a serialized server response. */
    void getPetByIdFinished(OAIPet summary);
    /** Signal is emitted, if getPetById() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void getPetByIdErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if updatePet() request completed successfully. The \a summary contains a serialized server response. */
    void updatePetFinished(OAIPet summary);
    /** Signal is emitted, if updatePet() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void updatePetErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if updatePetWithForm() request completed successfully. */
    void updatePetWithFormFinished();
    /** Signal is emitted, if updatePetWithForm() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void updatePetWithFormErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if uploadFile() request completed successfully. The \a summary contains a serialized server response. */
    void uploadFileFinished(OAIApiResponse summary);
    /** Signal is emitted, if uploadFile() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void uploadFileErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
};

} // namespace OpenAPI
#endif
