/**
 * OpenAPI Petstore
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QtOAICategory.h"
#include "QtOAIHelpers.h"

#include <QtCore/qdebug.h>

namespace QtOpenAPI {

QtOAICategory::QtOAICategory(const QString &json)
{
    this->initializeModel();
    this->fromJson(json);
}

QtOAICategory::QtOAICategory()
{
    this->initializeModel();
}

QtOAICategory::~QtOAICategory()
{
}

void QtOAICategory::initializeModel()
{

    m_idIsSet = false;
    m_idIsValid = false;

    m_nameIsSet = false;
    m_nameIsValid = false;
}

void QtOAICategory::fromJson(const QString &jsonString)
{
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void QtOAICategory::fromJsonObject(const QJsonObject &json)
{

    m_idIsValid = ::QtOpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_idIsSet = !json[QString("id")].isNull() && m_idIsValid;

    m_nameIsValid = ::QtOpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_nameIsSet = !json[QString("name")].isNull() && m_nameIsValid;
}

QString QtOAICategory::asJson() const
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson(QJsonDocument::Compact);
    return QString(bytes);
}

QJsonObject QtOAICategory::asJsonObject() const
{
    QJsonObject obj;
    if (m_idIsSet) {
        obj.insert(QString("id"), ::QtOpenAPI::toJsonValue(m_id));
    }
    if (m_nameIsSet) {
        obj.insert(QString("name"), ::QtOpenAPI::toJsonValue(m_name));
    }
    return obj;
}

qint64 QtOAICategory::getId() const
{
    return m_id;
}
void QtOAICategory::setId(const qint64 &id)
{
    m_id = id;
    m_idIsSet = true;
    m_idIsValid = true;
}

bool QtOAICategory::isIdSet() const
{
    return m_idIsSet;
}

bool QtOAICategory::isIdValid() const
{
    return m_idIsValid;
}

QString QtOAICategory::getName() const
{
    return m_name;
}
void QtOAICategory::setName(const QString &name)
{
    m_name = name;
    m_nameIsSet = true;
    m_nameIsValid = true;
}

bool QtOAICategory::isNameSet() const
{
    return m_nameIsSet;
}

bool QtOAICategory::isNameValid() const
{
    return m_nameIsValid;
}

bool QtOAICategory::isSet() const
{
    bool isObjectUpdated = false;
    do {
        if (m_idIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_nameIsSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool QtOAICategory::isValid() const
{
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace QtOpenAPI
