/**
 * OpenAPI Petstore
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QtOAIOrder.h
 *
 * An order for a pets from the pet store
 */

#ifndef QtOAIOrder_H
#define QtOAIOrder_H

#include "QtOAIExports.h"
#include "QtOAIObject.h"

#include <QDateTime>
#include <QString>

namespace QtOpenAPI {

class QtOAI_EXPORT QtOAIOrder : public QtOAIObject {
    Q_GADGET

    Q_PROPERTY(qint64 getId READ getId WRITE setId)
    Q_PROPERTY(qint64 getPetId READ getPetId WRITE setPetId)
    Q_PROPERTY(qint32 getQuantity READ getQuantity WRITE setQuantity)
    Q_PROPERTY(QDateTime getShipDate READ getShipDate WRITE setShipDate)
    Q_PROPERTY(QString getStatus READ getStatus WRITE setStatus)
    Q_PROPERTY(bool isComplete READ isComplete WRITE setComplete)
public:
    QtOAIOrder();
    QtOAIOrder(const QString &json);
    ~QtOAIOrder() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(const QJsonObject &json) override;
    void fromJson(const QString &jsonString) override;

    qint64 getId() const;
    void setId(const qint64 &id);
    bool isIdSet() const;
    bool isIdValid() const;

    qint64 getPetId() const;
    void setPetId(const qint64 &petId);
    bool isPetIdSet() const;
    bool isPetIdValid() const;

    qint32 getQuantity() const;
    void setQuantity(const qint32 &quantity);
    bool isQuantitySet() const;
    bool isQuantityValid() const;

    QDateTime getShipDate() const;
    void setShipDate(const QDateTime &shipDate);
    bool isShipDateSet() const;
    bool isShipDateValid() const;

    QString getStatus() const;
    void setStatus(const QString &status);
    bool isStatusSet() const;
    bool isStatusValid() const;

    bool isComplete() const;
    void setComplete(const bool &complete);
    bool isCompleteSet() const;
    bool isCompleteValid() const;

    bool isSet() const override;
    bool isValid() const override;

private:
    void initializeModel();

    qint64 m_id;
    bool m_idIsSet;
    bool m_idIsValid;

    qint64 m_petId;
    bool m_petIdIsSet;
    bool m_petIdIsValid;

    qint32 m_quantity;
    bool m_quantityIsSet;
    bool m_quantityIsValid;

    QDateTime m_shipDate;
    bool m_shipDateIsSet;
    bool m_shipDateIsValid;

    QString m_status;
    bool m_statusIsSet;
    bool m_statusIsValid;

    bool m_complete;
    bool m_completeIsSet;
    bool m_completeIsValid;
};

} // namespace QtOpenAPI

Q_DECLARE_METATYPE(QtOpenAPI::QtOAIOrder)

#endif // QtOAIOrder_H
