/**
 * OpenAPI Petstore
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QtOAIUserApi.h"
#include "QtOAIServerConfiguration.h"

#include <QtCore/qanystringview.h>
#include <QtCore/qjsonarray.h>
#include <QtCore/qjsondocument.h>
#include <QtNetwork/qhttpmultipart.h>
#include <QtNetwork/qnetworkaccessmanager.h>
#include <QtNetwork/qnetworkreply.h>
#include <QtNetwork/qnetworkrequestfactory.h>
#include <QtNetwork/qrestaccessmanager.h>

using namespace Qt::StringLiterals;

namespace QtOpenAPI {

QtOAIUserApi::QtOAIUserApi(QObject *parent)
    : QtOAIBaseApi(parent)
{
    initializeServerConfigs();
}

QtOAIUserApi::~QtOAIUserApi()
{
}

void QtOAIUserApi::initializeServerConfigs()
{
    //Default server
    QList<QtOAIServerConfiguration> defaultConf = QList<QtOAIServerConfiguration>();
    //varying endpoint server
    defaultConf.append(QtOAIServerConfiguration(
    QUrl("http://127.0.0.1:9080/v2"),
    "No description provided",
    QMap<QString, QtOAIServerVariable>()));
    m_serverConfigs.insert("createInQueryMap", defaultConf);
    m_serverIndices.insert("createInQueryMap", 0);
    m_serverConfigs.insert("createUser", defaultConf);
    m_serverIndices.insert("createUser", 0);
    m_serverConfigs.insert("createUsersWithArrayInput", defaultConf);
    m_serverIndices.insert("createUsersWithArrayInput", 0);
    m_serverConfigs.insert("createUsersWithListInput", defaultConf);
    m_serverIndices.insert("createUsersWithListInput", 0);
    m_serverConfigs.insert("deleteUser", defaultConf);
    m_serverIndices.insert("deleteUser", 0);
    m_serverConfigs.insert("getUserByName", defaultConf);
    m_serverIndices.insert("getUserByName", 0);
    m_serverConfigs.insert("loginUser", defaultConf);
    m_serverIndices.insert("loginUser", 0);
    m_serverConfigs.insert("logoutUser", defaultConf);
    m_serverIndices.insert("logoutUser", 0);
    m_serverConfigs.insert("updateUser", defaultConf);
    m_serverIndices.insert("updateUser", 0);
}

/**
* \fn virtual void QtOAIUserApi::createInQueryMap(const QMap<QString, QString> &username)
* 'createInQueryMap' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] username QMap<QString, QString> [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::createInQueryMap(const QMap<QString, QString> &username, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'createInQueryMap' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    createInQueryMap(username, this, [&](const QRestReply &reply) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual createInQueryMapWithDataImpl() in derived class.
* The virtual createInQueryMapWithDataImpl() is being called by the template
* function.

* @param[in] username QMap<QString, QString> [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::createInQueryMapCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by createInQueryMapFinished() or
* being returned as a callback parameter of createInQueryMap() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::createInQueryMapWithDataImpl(const QMap<QString, QString> &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the createInQueryMap() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking createInQueryMap() operation calls.

* @param[in] username QMap<QString, QString> [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::createInQueryMapWithDataImpl(const QMap<QString, QString> &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["createInQueryMap"][m_serverIndices.value("createInQueryMap")].serverUrl();
    QString fullPath = "/user/createInQueryMap";
    m_networkFactory->setBaseUrl(serverUrl);
    int queryParamCounter = 0;
    {
        [[maybe_unused]] QString paramString;
        QString queryStyle = "form";
        if (queryStyle.isEmpty())
            queryStyle = "form";
        const QString queryPrefix = getParamStylePrefix(queryStyle);
        [[maybe_unused]] const QString queryDelimiter = getParamStyleDelimiter(queryStyle, true);
        const QString querySuffix = getParamStyleSuffix(queryStyle, u"username"_s, true, (!false && !false));
        [[maybe_unused]] const QString queryAssignOperator = getParamStyleAssignOperator(queryStyle, true, (!false && !false));
        paramString = querySuffix;
        if ((fullPath.indexOf("?") != fullPath.size() - 1) && (queryParamCounter == 0))
            fullPath.append(queryPrefix);
        {
            if (queryParamCounter > 0)
                fullPath.append("&");
            paramString.append(::QtOpenAPI::toStringValue(username, queryAssignOperator, queryDelimiter));
            fullPath.append(paramString);
            queryParamCounter++;
        }
    }
    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "POST");
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            createInQueryMapCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit createInQueryMapErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::createInQueryMapCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply) };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit createInQueryMapFinished();
}

/**
* \fn virtual void QtOAIUserApi::createUser(const QtOAIUser &qtOAIUser)
* 'createUser' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] qtOAIUser QtOAIUser [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::createUser(const QtOAIUser &qtOAIUser, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'createUser' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    createUser(qtOAIUser, this, [&](const QRestReply &reply) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual createUserWithDataImpl() in derived class.
* The virtual createUserWithDataImpl() is being called by the template
* function.

* @param[in] qtOAIUser QtOAIUser [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::createUserCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by createUserFinished() or
* being returned as a callback parameter of createUser() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::createUserWithDataImpl(const QtOAIUser &qtOAIUser, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the createUser() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking createUser() operation calls.

* @param[in] qtOAIUser QtOAIUser [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::createUserWithDataImpl(const QtOAIUser &qtOAIUser, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["createUser"][m_serverIndices.value("createUser")].serverUrl();
    QString fullPath = "/user";
    m_networkFactory->setBaseUrl(serverUrl);
    if (m_apiKeys.contains("api_key"_L1)) {
        setHeader("api_key"_L1, QAnyStringView(m_apiKeys.find("api_key"_L1).value()));
    }
    

    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "POST");
    {
        input.m_headers.replaceOrAppend(QHttpHeaders::WellKnownHeader::ContentType, "application/json"_L1);
        QByteArray output = qtOAIUser.asJson().toUtf8();
        input.m_requestBody.append(output);
    }
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            createUserCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit createUserErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::createUserCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply) };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit createUserFinished();
}

/**
* \fn virtual void QtOAIUserApi::createUsersWithArrayInput(const QList<QtOAIUser> &qtOAIUser)
* 'createUsersWithArrayInput' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] qtOAIUser QList<QtOAIUser> [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::createUsersWithArrayInput(const QList<QtOAIUser> &qtOAIUser, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'createUsersWithArrayInput' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    createUsersWithArrayInput(qtOAIUser, this, [&](const QRestReply &reply) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual createUsersWithArrayInputWithDataImpl() in derived class.
* The virtual createUsersWithArrayInputWithDataImpl() is being called by the template
* function.

* @param[in] qtOAIUser QList<QtOAIUser> [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::createUsersWithArrayInputCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by createUsersWithArrayInputFinished() or
* being returned as a callback parameter of createUsersWithArrayInput() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::createUsersWithArrayInputWithDataImpl(const QList<QtOAIUser> &qtOAIUser, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the createUsersWithArrayInput() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking createUsersWithArrayInput() operation calls.

* @param[in] qtOAIUser QList<QtOAIUser> [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::createUsersWithArrayInputWithDataImpl(const QList<QtOAIUser> &qtOAIUser, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["createUsersWithArrayInput"][m_serverIndices.value("createUsersWithArrayInput")].serverUrl();
    QString fullPath = "/user/createWithArray";
    m_networkFactory->setBaseUrl(serverUrl);
    if (m_apiKeys.contains("api_key"_L1)) {
        setHeader("api_key"_L1, QAnyStringView(m_apiKeys.find("api_key"_L1).value()));
    }
    

    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "POST");
    {
        input.m_headers.replaceOrAppend(QHttpHeaders::WellKnownHeader::ContentType, "application/json"_L1);
        QJsonDocument doc(::QtOpenAPI::toJsonValue(qtOAIUser).toArray());
        QByteArray bytes = doc.toJson(QJsonDocument::Compact);
        input.m_requestBody.append(bytes);
    }
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            createUsersWithArrayInputCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit createUsersWithArrayInputErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::createUsersWithArrayInputCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply) };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit createUsersWithArrayInputFinished();
}

/**
* \fn virtual void QtOAIUserApi::createUsersWithListInput(const QList<QtOAIUser> &qtOAIUser)
* 'createUsersWithListInput' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] qtOAIUser QList<QtOAIUser> [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::createUsersWithListInput(const QList<QtOAIUser> &qtOAIUser, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'createUsersWithListInput' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    createUsersWithListInput(qtOAIUser, this, [&](const QRestReply &reply) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual createUsersWithListInputWithDataImpl() in derived class.
* The virtual createUsersWithListInputWithDataImpl() is being called by the template
* function.

* @param[in] qtOAIUser QList<QtOAIUser> [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::createUsersWithListInputCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by createUsersWithListInputFinished() or
* being returned as a callback parameter of createUsersWithListInput() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::createUsersWithListInputWithDataImpl(const QList<QtOAIUser> &qtOAIUser, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the createUsersWithListInput() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking createUsersWithListInput() operation calls.

* @param[in] qtOAIUser QList<QtOAIUser> [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::createUsersWithListInputWithDataImpl(const QList<QtOAIUser> &qtOAIUser, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["createUsersWithListInput"][m_serverIndices.value("createUsersWithListInput")].serverUrl();
    QString fullPath = "/user/createWithList";
    m_networkFactory->setBaseUrl(serverUrl);
    if (m_apiKeys.contains("api_key"_L1)) {
        setHeader("api_key"_L1, QAnyStringView(m_apiKeys.find("api_key"_L1).value()));
    }
    

    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "POST");
    {
        input.m_headers.replaceOrAppend(QHttpHeaders::WellKnownHeader::ContentType, "application/json"_L1);
        QJsonDocument doc(::QtOpenAPI::toJsonValue(qtOAIUser).toArray());
        QByteArray bytes = doc.toJson(QJsonDocument::Compact);
        input.m_requestBody.append(bytes);
    }
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            createUsersWithListInputCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit createUsersWithListInputErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::createUsersWithListInputCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply) };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit createUsersWithListInputFinished();
}

/**
* \fn virtual void QtOAIUserApi::deleteUser(const QtOAIUser &username)
* 'deleteUser' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] username QtOAIUser [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::deleteUser(const QtOAIUser &username, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'deleteUser' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    deleteUser(username, this, [&](const QRestReply &reply) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual deleteUserWithDataImpl() in derived class.
* The virtual deleteUserWithDataImpl() is being called by the template
* function.

* @param[in] username QtOAIUser [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::deleteUserCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by deleteUserFinished() or
* being returned as a callback parameter of deleteUser() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::deleteUserWithDataImpl(const QtOAIUser &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the deleteUser() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking deleteUser() operation calls.

* @param[in] username QtOAIUser [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::deleteUserWithDataImpl(const QtOAIUser &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["deleteUser"][m_serverIndices.value("deleteUser")].serverUrl();
    QString fullPath = "/user/{username}";
    m_networkFactory->setBaseUrl(serverUrl);
    if (m_apiKeys.contains("api_key"_L1)) {
        setHeader("api_key"_L1, QAnyStringView(m_apiKeys.find("api_key"_L1).value()));
    }
    
    {
        QString usernamePathParam = QString("{%1}").arg("username");
        QString pathStyle = "simple";
        if (pathStyle.isEmpty())
            pathStyle = "simple";
        const QString pathPrefix = getParamStylePrefix(pathStyle);
        const QString pathDelimiter = getParamStyleDelimiter(pathStyle, false);
        [[maybe_unused]] const QString assignOperator = getParamStyleAssignOperator(pathStyle, false, (!false && !false));
        const QString pathSuffix = getParamStyleSuffix(pathStyle, u"username"_s, false, (!false && !false));
        QString paramString = pathPrefix + pathSuffix;
        paramString = pathPrefix + serializeJsonValue(QJsonValue(username.asJsonObject()), pathStyle, false, pathSuffix, assignOperator, pathDelimiter);
        // In case style=matrix and paramString is empty due to any reasons,
        // we serialize it like undefined value and delete '='.
        // Described here: https://spec.openapis.org/oas/v3.1.1.html#style-values
        if ((paramString == pathPrefix + pathSuffix) && QString("simple") == "matrix"_L1)
            paramString.chop(1);
        fullPath.replace(usernamePathParam, paramString);
    }

    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "DELETE");
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            deleteUserCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit deleteUserErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::deleteUserCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply) };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit deleteUserFinished();
}

/**
* \fn virtual void QtOAIUserApi::getUserByName(const QMap<QString, qint32> &username)
* 'getUserByName' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] username QMap<QString, qint32> [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::getUserByName(const QMap<QString, qint32> &username, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'getUserByName' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    getUserByName(username, this, [&](const QRestReply &reply, const QtOAIUser &summary) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual getUserByNameWithDataImpl() in derived class.
* The virtual getUserByNameWithDataImpl() is being called by the template
* function.

* @param[in] username QMap<QString, qint32> [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::getUserByNameCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by getUserByNameFinished() or
* being returned as a callback parameter of getUserByName() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::getUserByNameWithDataImpl(const QMap<QString, qint32> &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the getUserByName() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking getUserByName() operation calls.

* @param[in] username QMap<QString, qint32> [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::getUserByNameWithDataImpl(const QMap<QString, qint32> &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["getUserByName"][m_serverIndices.value("getUserByName")].serverUrl();
    QString fullPath = "/user/{username}";
    m_networkFactory->setBaseUrl(serverUrl);
    {
        QString usernamePathParam = QString("{%1}").arg("username");
        QString pathStyle = "simple";
        if (pathStyle.isEmpty())
            pathStyle = "simple";
        const QString pathPrefix = getParamStylePrefix(pathStyle);
        const QString pathDelimiter = getParamStyleDelimiter(pathStyle, false);
        [[maybe_unused]] const QString assignOperator = getParamStyleAssignOperator(pathStyle, false, (!false && !false));
        const QString pathSuffix = getParamStyleSuffix(pathStyle, u"username"_s, false, (!false && !false));
        QString paramString = pathPrefix + pathSuffix;
        paramString.append(::QtOpenAPI::toStringValue(username, assignOperator, pathDelimiter));
        // In case style=matrix and paramString is empty due to any reasons,
        // we serialize it like undefined value and delete '='.
        // Described here: https://spec.openapis.org/oas/v3.1.1.html#style-values
        if ((paramString == pathPrefix + pathSuffix) && QString("simple") == "matrix"_L1)
            paramString.chop(1);
        fullPath.replace(usernamePathParam, paramString);
    }

    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "GET");
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            getUserByNameCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit getUserByNameErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QtOAIUser empty;
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl, &empty };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::getUserByNameCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    const QByteArray response = QtOAIHttpRequestWorker::parseResponse(reply, m_workingDirectory);
    QtOAIUser output(response);
    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply), &output };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit getUserByNameFinished(output);
}

/**
* \fn virtual void QtOAIUserApi::loginUser(const ::QtOpenAPI::OptionalParam<QString> &username = ::QtOpenAPI::OptionalParam<QString>(), const ::QtOpenAPI::OptionalParam<QString> &password = ::QtOpenAPI::OptionalParam<QString>())
* 'loginUser' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] username QString [optional]
* @param[in] password QString [optional]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::loginUser(const ::QtOpenAPI::OptionalParam<QString> &username = ::QtOpenAPI::OptionalParam<QString>(), const ::QtOpenAPI::OptionalParam<QString> &password = ::QtOpenAPI::OptionalParam<QString>(), const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'loginUser' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    loginUser(username, password, this, [&](const QRestReply &reply, const QString &summary) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual loginUserWithDataImpl() in derived class.
* The virtual loginUserWithDataImpl() is being called by the template
* function.

* @param[in] username QString [optional]
* @param[in] password QString [optional]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::loginUserCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by loginUserFinished() or
* being returned as a callback parameter of loginUser() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::loginUserWithDataImpl(const ::QtOpenAPI::OptionalParam<QString> &username, const ::QtOpenAPI::OptionalParam<QString> &password, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the loginUser() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking loginUser() operation calls.

* @param[in] username QString [optional]
* @param[in] password QString [optional]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::loginUserWithDataImpl(const ::QtOpenAPI::OptionalParam<QString> &username, const ::QtOpenAPI::OptionalParam<QString> &password, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["loginUser"][m_serverIndices.value("loginUser")].serverUrl();
    QString fullPath = "/user/login";
    m_networkFactory->setBaseUrl(serverUrl);
    int queryParamCounter = 0;
    {
        [[maybe_unused]] QString paramString;
        QString queryStyle = "form";
        if (queryStyle.isEmpty())
            queryStyle = "form";
        const QString queryPrefix = getParamStylePrefix(queryStyle);
        [[maybe_unused]] const QString queryDelimiter = getParamStyleDelimiter(queryStyle, true);
        const QString querySuffix = getParamStyleSuffix(queryStyle, u"username"_s, true, (!true && !false));
        [[maybe_unused]] const QString queryAssignOperator = getParamStyleAssignOperator(queryStyle, true, (!true && !false));
        paramString = querySuffix;
        if ((fullPath.indexOf("?") != fullPath.size() - 1) && (queryParamCounter == 0))
            fullPath.append(queryPrefix);
        if (username.hasValue()) {
            if (queryParamCounter > 0)
                fullPath.append("&");
            fullPath.append(querySuffix + QUrl::toPercentEncoding(::QtOpenAPI::toStringValue(username.value())));
            queryParamCounter++;
        } else if (username.isNull()) {
            if (queryParamCounter > 0)
                fullPath.append("&");
            // style=form && explode=true && non-object => 'username' isn't used in serialization
            // style=form && explode=true && empty object => need to be 'username='
            // see https://spec.openapis.org/oas/v3.1.1.html#style-values
            if (queryStyle == "form")
                fullPath.append(u"username="_s);
            else
                fullPath.append(querySuffix);
            queryParamCounter++;
        }
    }
    {
        [[maybe_unused]] QString paramString;
        QString queryStyle = "form";
        if (queryStyle.isEmpty())
            queryStyle = "form";
        const QString queryPrefix = getParamStylePrefix(queryStyle);
        [[maybe_unused]] const QString queryDelimiter = getParamStyleDelimiter(queryStyle, true);
        const QString querySuffix = getParamStyleSuffix(queryStyle, u"password"_s, true, (!true && !false));
        [[maybe_unused]] const QString queryAssignOperator = getParamStyleAssignOperator(queryStyle, true, (!true && !false));
        paramString = querySuffix;
        if ((fullPath.indexOf("?") != fullPath.size() - 1) && (queryParamCounter == 0))
            fullPath.append(queryPrefix);
        if (password.hasValue()) {
            if (queryParamCounter > 0)
                fullPath.append("&");
            fullPath.append(querySuffix + QUrl::toPercentEncoding(::QtOpenAPI::toStringValue(password.value())));
            queryParamCounter++;
        } else if (password.isNull()) {
            if (queryParamCounter > 0)
                fullPath.append("&");
            // style=form && explode=true && non-object => 'password' isn't used in serialization
            // style=form && explode=true && empty object => need to be 'password='
            // see https://spec.openapis.org/oas/v3.1.1.html#style-values
            if (queryStyle == "form")
                fullPath.append(u"password="_s);
            else
                fullPath.append(querySuffix);
            queryParamCounter++;
        }
    }
    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "GET");
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            loginUserCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit loginUserErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QString empty;
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl, &empty };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::loginUserCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    const QByteArray response = QtOAIHttpRequestWorker::parseResponse(reply, m_workingDirectory);
    QString output;
    ::QtOpenAPI::fromStringValue(response, output);
    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply), &output };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit loginUserFinished(output);
}

/**
* \fn virtual void QtOAIUserApi::logoutUser(const QJsonValue &username)
* 'logoutUser' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] username QJsonValue [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::logoutUser(const QJsonValue &username, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'logoutUser' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    logoutUser(username, this, [&](const QRestReply &reply) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual logoutUserWithDataImpl() in derived class.
* The virtual logoutUserWithDataImpl() is being called by the template
* function.

* @param[in] username QJsonValue [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::logoutUserCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by logoutUserFinished() or
* being returned as a callback parameter of logoutUser() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::logoutUserWithDataImpl(const QJsonValue &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the logoutUser() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking logoutUser() operation calls.

* @param[in] username QJsonValue [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::logoutUserWithDataImpl(const QJsonValue &username, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["logoutUser"][m_serverIndices.value("logoutUser")].serverUrl();
    QString fullPath = "/user/logout";
    m_networkFactory->setBaseUrl(serverUrl);
    if (m_apiKeys.contains("api_key"_L1)) {
        setHeader("api_key"_L1, QAnyStringView(m_apiKeys.find("api_key"_L1).value()));
    }
    
    int queryParamCounter = 0;
    {
        [[maybe_unused]] QString paramString;
        QString queryStyle = "form";
        if (queryStyle.isEmpty())
            queryStyle = "form";
        const QString queryPrefix = getParamStylePrefix(queryStyle);
        [[maybe_unused]] const QString queryDelimiter = getParamStyleDelimiter(queryStyle, true);
        const QString querySuffix = getParamStyleSuffix(queryStyle, u"username"_s, true, username.type() == QJsonValue::Object);
        const QString queryAssignOperator = getParamStyleAssignOperator(queryStyle, true, username.type() == QJsonValue::Object);
        if ((fullPath.indexOf("?") != fullPath.size() - 1) && (queryParamCounter == 0))
            fullPath.append(queryPrefix);
        {
            if (queryParamCounter > 0)
                fullPath.append("&");
            paramString = serializeJsonValue(username, queryStyle, true, querySuffix, queryAssignOperator, queryDelimiter);
            fullPath.append(paramString);
            queryParamCounter++;
        }
    }
    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "GET");
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            logoutUserCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit logoutUserErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::logoutUserCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply) };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit logoutUserFinished();
}

/**
* \fn virtual void QtOAIUserApi::updateUser(const QString &username, const QtOAIUser &body)
* 'updateUser' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] username QString [required]
* @param[in] body QtOAIUser [required]
*/

/**
* \fn template < Functor, > void QtOAIUserApi::updateUser(const QString &username, const QtOAIUser &body, const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'updateUser' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    updateUser(username, body, this, [&](const QRestReply &reply, const QtOAIUser &summary) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual updateUserWithDataImpl() in derived class.
* The virtual updateUserWithDataImpl() is being called by the template
* function.

* @param[in] username QString [required]
* @param[in] body QtOAIUser [required]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIUserApi::updateUserCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by updateUserFinished() or
* being returned as a callback parameter of updateUser() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIUserApi::updateUserWithDataImpl(const QString &username, const QtOAIUser &body, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the updateUser() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking updateUser() operation calls.

* @param[in] username QString [required]
* @param[in] body QtOAIUser [required]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIUserApi::updateUserWithDataImpl(const QString &username, const QtOAIUser &body, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["updateUser"][m_serverIndices.value("updateUser")].serverUrl();
    QString fullPath = "/user/{username}";
    m_networkFactory->setBaseUrl(serverUrl);
    if (m_apiKeys.contains("api_key"_L1)) {
        setHeader("api_key"_L1, QAnyStringView(m_apiKeys.find("api_key"_L1).value()));
    }
    
    {
        QString usernamePathParam = QString("{%1}").arg("username");
        QString pathStyle = "simple";
        if (pathStyle.isEmpty())
            pathStyle = "simple";
        const QString pathPrefix = getParamStylePrefix(pathStyle);
        const QString pathDelimiter = getParamStyleDelimiter(pathStyle, false);
        [[maybe_unused]] const QString assignOperator = getParamStyleAssignOperator(pathStyle, false, (!true && !false));
        const QString pathSuffix = getParamStyleSuffix(pathStyle, u"username"_s, false, (!true && !false));
        QString paramString = pathPrefix + pathSuffix;
        paramString += QUrl::toPercentEncoding(::QtOpenAPI::toStringValue(username));
        // In case style=matrix and paramString is empty due to any reasons,
        // we serialize it like undefined value and delete '='.
        // Described here: https://spec.openapis.org/oas/v3.1.1.html#style-values
        if ((paramString == pathPrefix + pathSuffix) && QString("simple") == "matrix"_L1)
            paramString.chop(1);
        fullPath.replace(usernamePathParam, paramString);
    }
    int queryParamCounter = 0;
    {
        [[maybe_unused]] QString paramString;
        QString queryStyle = "form";
        if (queryStyle.isEmpty())
            queryStyle = "form";
        const QString queryPrefix = getParamStylePrefix(queryStyle);
        [[maybe_unused]] const QString queryDelimiter = getParamStyleDelimiter(queryStyle, true);
        const QString querySuffix = getParamStyleSuffix(queryStyle, u"body"_s, true, (!false && !false));
        [[maybe_unused]] const QString queryAssignOperator = getParamStyleAssignOperator(queryStyle, true, (!false && !false));
        paramString = querySuffix;
        if ((fullPath.indexOf("?") != fullPath.size() - 1) && (queryParamCounter == 0))
            fullPath.append(queryPrefix);
        {
            if (queryParamCounter > 0)
                fullPath.append("&");
            const QJsonObject parameter = body.asJsonObject();
            if (queryStyle == "deepObject") {
                qint32 index = 0;
                if (parameter.isEmpty())
                    qWarning() << "Serialized QJsonValue::Object is empty!";
                for (const QString& key : parameter.keys()) {
                    if (index > 0)
                        paramString.append(queryDelimiter);
                    paramString.append(::QtOpenAPI::optionParameterToString(QString("body") + QString("[") + key + QString("]"), queryAssignOperator, parameter.value(key)));
                    index++;
                }
            } else {
                paramString = serializeJsonValue(QJsonValue(parameter), queryStyle, true, querySuffix, queryAssignOperator, queryDelimiter);
            }
            // style=form && explode=true && non-object => 'body' isn't used in serialization
            // style=form && explode=true && empty object => need to be 'body='
            // see https://spec.openapis.org/oas/v3.1.1.html#style-values
            if (paramString.isEmpty() && queryStyle == "form")
                paramString = u"body="_s;
            fullPath.append(paramString);
            queryParamCounter++;
        }
    }
    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "PUT");
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            updateUserCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit updateUserErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QtOAIUser empty;
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl, &empty };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIUserApi::updateUserCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    const QByteArray response = QtOAIHttpRequestWorker::parseResponse(reply, m_workingDirectory);
    QtOAIUser output(response);
    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply), &output };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit updateUserFinished(output);
}

} // namespace QtOpenAPI
