/**
 * OpenAPI Petstore
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef QtOAI_QtOAIPetApi_H
#define QtOAI_QtOAIPetApi_H

#include "QtOAIBaseApi.h"
#include <QtNetwork/qrestreply.h>

#include <QString>
#include "QtOAIApiResponse.h"
#include "QtOAIHttpFileElement.h"
#include "QtOAIPet.h"

namespace QtOpenAPI {

class QtOAIPetApi : public QtOAIBaseApi {
    Q_OBJECT
public:
    QtOAIPetApi() : QtOAIPetApi(nullptr) {}
    explicit QtOAIPetApi(QObject *parent);
    ~QtOAIPetApi() override;

    void initializeServerConfigs();
public:
    /**
    * \internal
    * The auto-generated API:
    * void addPet(const QtOAIPet &qtOAIPet);
    * void addPet(const QtOAIPet &qtOAIPet, QObject *object, [&](const QRestReply &reply, const QtOAIPet &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(addPet, (const QtOAIPet &qtOAIPet), (qtOAIPet), (const QtOAIPet &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void deletePet(const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &apiKey);
    * void deletePet(const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &apiKey, QObject *object, [&](const QRestReply &reply){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_WITH_NO_RESPONSE_IMPL(deletePet, (const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &apiKey = ::QtOpenAPI::OptionalParam<QString>()), (petId, apiKey), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsByAgeAndPatience(const QList<qint32> &petData);
    * void findPetsByAgeAndPatience(const QList<qint32> &petData, QObject *object, [&](const QRestReply &reply, const QList<QtOAIPet> &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(findPetsByAgeAndPatience, (const QList<qint32> &petData), (petData), (const QList<QtOAIPet> &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsByStatus(const QList<QString> &status);
    * void findPetsByStatus(const QList<QString> &status, QObject *object, [&](const QRestReply &reply, const QList<QtOAIPet> &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(findPetsByStatus, (const QList<QString> &status), (status), (const QList<QtOAIPet> &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsByTags(const QList<QString> &tags);
    * void findPetsByTags(const QList<QString> &tags, QObject *object, [&](const QRestReply &reply, const QList<QtOAIPet> &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(findPetsByTags, (const QList<QString> &tags), (tags), (const QList<QtOAIPet> &), Q_DECL_DEPRECATED)

    /**
    * \internal
    * The auto-generated API:
    * void findPetsImageById(const qint64 &petId);
    * void findPetsImageById(const qint64 &petId, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(findPetsImageById, (const qint64 &petId), (petId), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void getJsonFile(const qint64 &petId);
    * void getJsonFile(const qint64 &petId, QObject *object, [&](const QRestReply &reply, const QtOAIHttpFileElement &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(getJsonFile, (const qint64 &petId), (petId), (const QtOAIHttpFileElement &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void getPetById(const qint64 &petId);
    * void getPetById(const qint64 &petId, QObject *object, [&](const QRestReply &reply, const QtOAIPet &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(getPetById, (const qint64 &petId), (petId), (const QtOAIPet &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void updatePet(const QtOAIPet &qtOAIPet);
    * void updatePet(const QtOAIPet &qtOAIPet, QObject *object, [&](const QRestReply &reply, const QtOAIPet &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(updatePet, (const QtOAIPet &qtOAIPet), (qtOAIPet), (const QtOAIPet &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void updatePetWithForm(const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &name, const ::QtOpenAPI::OptionalParam<QString> &status);
    * void updatePetWithForm(const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &name, const ::QtOpenAPI::OptionalParam<QString> &status, QObject *object, [&](const QRestReply &reply){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_WITH_NO_RESPONSE_IMPL(updatePetWithForm, (const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &name = ::QtOpenAPI::OptionalParam<QString>(), const ::QtOpenAPI::OptionalParam<QString> &status = ::QtOpenAPI::OptionalParam<QString>()), (petId, name, status), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void uploadFile(const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &additionalMetadata, const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &file);
    * void uploadFile(const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &additionalMetadata, const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &file, QObject *object, [&](const QRestReply &reply, const QtOAIApiResponse &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(uploadFile, (const qint64 &petId, const ::QtOpenAPI::OptionalParam<QString> &additionalMetadata = ::QtOpenAPI::OptionalParam<QString>(), const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &file = ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement>()), (petId, additionalMetadata, file), (const QtOAIApiResponse &), /* non-deprecated */)

Q_SIGNALS:
    /** Signal is emitted, if addPet() request completed successfully. The \a summary contains a serialized server response. */
    void addPetFinished(const QtOAIPet &summary);
    /** Signal is emitted, if addPet() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void addPetErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if deletePet() request completed successfully. */
    void deletePetFinished();
    /** Signal is emitted, if deletePet() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void deletePetErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsByAgeAndPatience() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsByAgeAndPatienceFinished(const QList<QtOAIPet> &summary);
    /** Signal is emitted, if findPetsByAgeAndPatience() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsByAgeAndPatienceErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsByStatus() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsByStatusFinished(const QList<QtOAIPet> &summary);
    /** Signal is emitted, if findPetsByStatus() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsByStatusErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsByTags() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsByTagsFinished(const QList<QtOAIPet> &summary);
    /** Signal is emitted, if findPetsByTags() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsByTagsErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if findPetsImageById() request completed successfully. The \a summary contains a serialized server response. */
    void findPetsImageByIdFinished(const QString &summary);
    /** Signal is emitted, if findPetsImageById() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void findPetsImageByIdErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if getJsonFile() request completed successfully. The \a summary contains a serialized server response. */
    void getJsonFileFinished(const QtOAIHttpFileElement &summary);
    /** Signal is emitted, if getJsonFile() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void getJsonFileErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if getPetById() request completed successfully. The \a summary contains a serialized server response. */
    void getPetByIdFinished(const QtOAIPet &summary);
    /** Signal is emitted, if getPetById() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void getPetByIdErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if updatePet() request completed successfully. The \a summary contains a serialized server response. */
    void updatePetFinished(const QtOAIPet &summary);
    /** Signal is emitted, if updatePet() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void updatePetErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if updatePetWithForm() request completed successfully. */
    void updatePetWithFormFinished();
    /** Signal is emitted, if updatePetWithForm() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void updatePetWithFormErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if uploadFile() request completed successfully. The \a summary contains a serialized server response. */
    void uploadFileFinished(const QtOAIApiResponse &summary);
    /** Signal is emitted, if uploadFile() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void uploadFileErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);

protected:
    QString m_testOperationPath;
    QByteArray m_requestContent;
};

} // namespace QtOpenAPI
#endif
