/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIHttpFileElement.h"

#include <QtCore/qdebug.h>
#include <QtCore/qfile.h>
#include <QtCore/qjsondocument.h>
#include <QtCore/qjsonobject.h>

namespace OpenAPI {

void OAIHttpFileElement::setMimeType(const QString &mime)
{
    m_mimeType = mime;
}

void OAIHttpFileElement::setFileName(const QString &name)
{
    m_localFilename = name;
}

void OAIHttpFileElement::setVariableName(const QString &name)
{
    m_variableName = name;
}

void OAIHttpFileElement::setRequestFileName(const QString &name)
{
    m_requestFilename = name;
}

bool OAIHttpFileElement::isSet() const {
    return !m_localFilename.isEmpty() || !m_requestFilename.isEmpty();
}

QString OAIHttpFileElement::asJson() const
{
    QFile file(m_localFilename);
    QByteArray bArray;
    bool result = false;
    if (file.exists()) {
        result = file.open(QIODevice::ReadOnly);
        bArray = file.readAll();
        file.close();
    }
    if (!result) {
        qDebug() << "Error opening file " << m_localFilename;
    }
    return QString(bArray);
}

QJsonValue OAIHttpFileElement::asJsonValue() const
{
    QFile file(m_localFilename);
    QByteArray bArray;
    bool result = false;
    if (file.exists()) {
        result = file.open(QIODevice::ReadOnly);
        bArray = file.readAll();
        file.close();
    }
    if (!result) {
        qDebug() << "Error opening file " << m_localFilename;
    }
    return QJsonDocument::fromJson(bArray.data()).object();
}

bool OAIHttpFileElement::fromStringValue(const QString &instr)
{
    QFile file(m_localFilename);
    bool result = false;
    if (file.exists()) {
        file.remove();
    }
    result = file.open(QIODevice::WriteOnly);
    file.write(instr.toUtf8());
    file.close();
    if (!result) {
        qDebug() << "Error creating file " << m_localFilename;
    }
    return result;
}

bool OAIHttpFileElement::fromJsonValue(const QJsonValue &jval)
{
    QFile file(m_localFilename);
    bool result = false;
    if (file.exists()) {
        file.remove();
    }
    result = file.open(QIODevice::WriteOnly);
    file.write(QJsonDocument(jval.toObject()).toJson(QJsonDocument::Compact));
    file.close();
    if (!result) {
        qDebug() << "Error creating file " << m_localFilename;
    }
    return result;
}

QByteArray OAIHttpFileElement::asByteArray() const
{
    QFile file(m_localFilename);
    QByteArray bArray;
    bool result = false;
    if (file.exists()) {
        result = file.open(QIODevice::ReadOnly);
        bArray = file.readAll();
        file.close();
    }
    if (!result) {
        qDebug() << "Error opening file " << m_localFilename;
    }
    return bArray;
}

bool OAIHttpFileElement::fromByteArray(const QByteArray &bytes)
{
    QFile file(m_localFilename);
    bool result = false;
    if (file.exists()) {
        file.remove();
    }
    result = file.open(QIODevice::WriteOnly);
    file.write(bytes);
    file.close();
    if (!result) {
        qDebug() << "Error creating file " << m_localFilename;
    }
    return result;
}

bool OAIHttpFileElement::saveToFile(const QString &varName, const QString &localFName, const QString &reqFname, const QString &mime, const QByteArray &bytes)
{
    setMimeType(mime);
    setFileName(localFName);
    setVariableName(varName);
    setRequestFileName(reqFname);
    return fromByteArray(bytes);
}

QByteArray OAIHttpFileElement::loadFromFile(const QString &varName, const QString &localFName, const QString &reqFname, const QString &mime)
{
    setMimeType(mime);
    setFileName(localFName);
    setVariableName(varName);
    setRequestFileName(reqFname);
    return asByteArray();
}

} // namespace OpenAPI
