/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPostMultiPartData_request_formObject.h"
#include "OAIHelpers.h"

#include <QtCore/qdebug.h>

namespace OpenAPI {

OAIPostMultiPartData_request_formObject::OAIPostMultiPartData_request_formObject(const QString &json)
{
    this->initializeModel();
    this->fromJson(json);
}

OAIPostMultiPartData_request_formObject::OAIPostMultiPartData_request_formObject()
{
    this->initializeModel();
}

OAIPostMultiPartData_request_formObject::~OAIPostMultiPartData_request_formObject()
{
}

void OAIPostMultiPartData_request_formObject::initializeModel()
{

    m_objectIdIsSet = false;
    m_objectIdIsValid = false;

    m_objectNameIsSet = false;
    m_objectNameIsValid = false;
}

void OAIPostMultiPartData_request_formObject::fromJson(const QString &jsonString)
{
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPostMultiPartData_request_formObject::fromJsonObject(const QJsonObject &json)
{

    m_objectIdIsValid = ::OpenAPI::fromJsonValue(m_objectId, json[QString("objectId")]);
    m_objectIdIsSet = !json[QString("objectId")].isNull() && m_objectIdIsValid;

    m_objectNameIsValid = ::OpenAPI::fromJsonValue(m_objectName, json[QString("objectName")]);
    m_objectNameIsSet = !json[QString("objectName")].isNull() && m_objectNameIsValid;
}

QString OAIPostMultiPartData_request_formObject::asJson() const
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson(QJsonDocument::Compact);
    return QString(bytes);
}

QJsonObject OAIPostMultiPartData_request_formObject::asJsonObject() const
{
    QJsonObject obj;
    if (m_objectIdIsSet) {
        obj.insert(QString("objectId"), ::OpenAPI::toJsonValue(m_objectId));
    }
    if (m_objectNameIsSet) {
        obj.insert(QString("objectName"), ::OpenAPI::toJsonValue(m_objectName));
    }
    return obj;
}

qint32 OAIPostMultiPartData_request_formObject::getObjectId() const
{
    return m_objectId;
}
void OAIPostMultiPartData_request_formObject::setObjectId(const qint32 &objectId)
{
    m_objectId = objectId;
    m_objectIdIsSet = true;
}

bool OAIPostMultiPartData_request_formObject::isObjectIdSet() const
{
    return m_objectIdIsSet;
}

bool OAIPostMultiPartData_request_formObject::isObjectIdValid() const
{
    return m_objectIdIsValid;
}

QString OAIPostMultiPartData_request_formObject::getObjectName() const
{
    return m_objectName;
}
void OAIPostMultiPartData_request_formObject::setObjectName(const QString &objectName)
{
    m_objectName = objectName;
    m_objectNameIsSet = true;
}

bool OAIPostMultiPartData_request_formObject::isObjectNameSet() const
{
    return m_objectNameIsSet;
}

bool OAIPostMultiPartData_request_formObject::isObjectNameValid() const
{
    return m_objectNameIsValid;
}

bool OAIPostMultiPartData_request_formObject::isSet() const
{
    bool isObjectUpdated = false;
    do {
        if (m_objectIdIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_objectNameIsSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPostMultiPartData_request_formObject::isValid() const
{
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
