/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAITestApi_H
#define OAI_OAITestApi_H

#include "OAIBaseApi.h"
#include <QtNetwork/qrestreply.h>

#include "OAIHttpFileElement.h"
#include "OAIPostApplicationJsonSeveralObjects_request.h"
#include "OAIUser.h"
#include <QMap>
#include <QString>

namespace OpenAPI {

class OAITestApi : public OAIBaseApi {
    Q_OBJECT
public:
    OAITestApi() : OAITestApi(nullptr) {}
    explicit OAITestApi(QObject *parent);
    ~OAITestApi() override;

    void initializeServerConfigs();
public:
    /**
    * \internal
    * The auto-generated API:
    * void binaryType(const ::OpenAPI::OptionalParam<OAIHttpFileElement> &body);
    * void binaryType(const ::OpenAPI::OptionalParam<OAIHttpFileElement> &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(binaryType, (const ::OpenAPI::OptionalParam<OAIHttpFileElement> &body = ::OpenAPI::OptionalParam<OAIHttpFileElement>()), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonArray(const QList<OAIUser> &oAIUser);
    * void postApplicationJsonArray(const QList<OAIUser> &oAIUser, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postApplicationJsonArray, (const QList<OAIUser> &oAIUser), (oAIUser), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonBool(const bool &body);
    * void postApplicationJsonBool(const bool &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postApplicationJsonBool, (const bool &body), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonInt(const qint32 &body);
    * void postApplicationJsonInt(const qint32 &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postApplicationJsonInt, (const qint32 &body), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonMap(const QMap<QString, OAIUser> &requestBody);
    * void postApplicationJsonMap(const QMap<QString, OAIUser> &requestBody, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postApplicationJsonMap, (const QMap<QString, OAIUser> &requestBody), (requestBody), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonObject(const OAIUser &oAIUser);
    * void postApplicationJsonObject(const OAIUser &oAIUser, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postApplicationJsonObject, (const OAIUser &oAIUser), (oAIUser), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonSeveralObjects(const OAIPostApplicationJsonSeveralObjects_request &oAIPostApplicationJsonSeveralObjectsRequest);
    * void postApplicationJsonSeveralObjects(const OAIPostApplicationJsonSeveralObjects_request &oAIPostApplicationJsonSeveralObjectsRequest, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postApplicationJsonSeveralObjects, (const OAIPostApplicationJsonSeveralObjects_request &oAIPostApplicationJsonSeveralObjectsRequest), (oAIPostApplicationJsonSeveralObjectsRequest), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonString(const ::OpenAPI::OptionalParam<QString> &body);
    * void postApplicationJsonString(const ::OpenAPI::OptionalParam<QString> &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postApplicationJsonString, (const ::OpenAPI::OptionalParam<QString> &body = ::OpenAPI::OptionalParam<QString>()), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postPlainTextType(const QString &body);
    * void postPlainTextType(const QString &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    OAI_ADD_OPERATION_IMPL(postPlainTextType, (const QString &body), (body), (const QString &), /* non-deprecated */)

Q_SIGNALS:
    /** Signal is emitted, if binaryType() request completed successfully. The \a summary contains a serialized server response. */
    void binaryTypeFinished(const QString &summary);
    /** Signal is emitted, if binaryType() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void binaryTypeErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonArray() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonArrayFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonArray() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonArrayErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonBool() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonBoolFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonBool() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonBoolErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonInt() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonIntFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonInt() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonIntErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonMap() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonMapFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonMap() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonMapErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonObject() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonObjectFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonObject() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonObjectErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonSeveralObjects() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonSeveralObjectsFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonSeveralObjects() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonSeveralObjectsErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonString() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonStringFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonString() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonStringErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postPlainTextType() request completed successfully. The \a summary contains a serialized server response. */
    void postPlainTextTypeFinished(const QString &summary);
    /** Signal is emitted, if postPlainTextType() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postPlainTextTypeErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);

protected:
    QString m_testOperationPath;
    QByteArray m_requestContent;
};

} // namespace OpenAPI
#endif
