/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef QtOAI_QtOAITestApi_H
#define QtOAI_QtOAITestApi_H

#include "QtOAIBaseApi.h"
#include "QtOAIExports.h"
#include <QtNetwork/qrestreply.h>

#include <QMap>
#include <QString>
#include "QtOAIHttpFileElement.h"
#include "QtOAIPostApplicationJsonSeveralObjects_request.h"
#include "QtOAIPostMultiPartData_request_formObject.h"
#include "QtOAIUser.h"

namespace QtOpenAPI {

class QtOAI_EXPORT QtOAITestApi : public QtOAIBaseApi {
    Q_OBJECT
public:
    QtOAITestApi() : QtOAITestApi(nullptr) {}
    explicit QtOAITestApi(QObject *parent);
    ~QtOAITestApi() override;

    void initializeServerConfigs();
public:
    /**
    * \internal
    * The auto-generated API:
    * void binaryType(const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &body);
    * void binaryType(const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(binaryType, (const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &body = ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement>()), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonArray(const QList<QtOAIUser> &qtOAIUser);
    * void postApplicationJsonArray(const QList<QtOAIUser> &qtOAIUser, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postApplicationJsonArray, (const QList<QtOAIUser> &qtOAIUser), (qtOAIUser), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonBool(const bool &body);
    * void postApplicationJsonBool(const bool &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postApplicationJsonBool, (const bool &body), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonInt(const qint32 &body);
    * void postApplicationJsonInt(const qint32 &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postApplicationJsonInt, (const qint32 &body), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonMap(const QMap<QString, QtOAIUser> &requestBody);
    * void postApplicationJsonMap(const QMap<QString, QtOAIUser> &requestBody, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postApplicationJsonMap, (const QMap<QString, QtOAIUser> &requestBody), (requestBody), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonObject(const QtOAIUser &qtOAIUser);
    * void postApplicationJsonObject(const QtOAIUser &qtOAIUser, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postApplicationJsonObject, (const QtOAIUser &qtOAIUser), (qtOAIUser), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonSeveralObjects(const QtOAIPostApplicationJsonSeveralObjects_request &qtOAIPostApplicationJsonSeveralObjectsRequest);
    * void postApplicationJsonSeveralObjects(const QtOAIPostApplicationJsonSeveralObjects_request &qtOAIPostApplicationJsonSeveralObjectsRequest, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postApplicationJsonSeveralObjects, (const QtOAIPostApplicationJsonSeveralObjects_request &qtOAIPostApplicationJsonSeveralObjectsRequest), (qtOAIPostApplicationJsonSeveralObjectsRequest), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postApplicationJsonString(const ::QtOpenAPI::OptionalParam<QString> &body);
    * void postApplicationJsonString(const ::QtOpenAPI::OptionalParam<QString> &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postApplicationJsonString, (const ::QtOpenAPI::OptionalParam<QString> &body = ::QtOpenAPI::OptionalParam<QString>()), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postMultiPartData(const QString &formId, const QList<QtOAIUser> &formAddresses, const ::QtOpenAPI::OptionalParam<qint32> &formIndex, const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &formProfileImage, const ::QtOpenAPI::OptionalParam<QtOAIPostMultiPartData_request_formObject> &formObject, const ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>> &formMap);
    * void postMultiPartData(const QString &formId, const QList<QtOAIUser> &formAddresses, const ::QtOpenAPI::OptionalParam<qint32> &formIndex, const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &formProfileImage, const ::QtOpenAPI::OptionalParam<QtOAIPostMultiPartData_request_formObject> &formObject, const ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>> &formMap, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postMultiPartData, (const QString &formId, const QList<QtOAIUser> &formAddresses, const ::QtOpenAPI::OptionalParam<qint32> &formIndex = ::QtOpenAPI::OptionalParam<qint32>(), const ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement> &formProfileImage = ::QtOpenAPI::OptionalParam<QtOAIHttpFileElement>(), const ::QtOpenAPI::OptionalParam<QtOAIPostMultiPartData_request_formObject> &formObject = ::QtOpenAPI::OptionalParam<QtOAIPostMultiPartData_request_formObject>(), const ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>> &formMap = ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>>()), (formId, formAddresses, formIndex, formProfileImage, formObject, formMap), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postPlainTextType(const QString &body);
    * void postPlainTextType(const QString &body, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postPlainTextType, (const QString &body), (body), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postUrlEncodedFields(const ::QtOpenAPI::OptionalParam<QString> &name, const ::QtOpenAPI::OptionalParam<qint32> &status, const ::QtOpenAPI::OptionalParam<bool> &availability, const ::QtOpenAPI::OptionalParam<QList<QString>> &visits, const ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>> &mapfield);
    * void postUrlEncodedFields(const ::QtOpenAPI::OptionalParam<QString> &name, const ::QtOpenAPI::OptionalParam<qint32> &status, const ::QtOpenAPI::OptionalParam<bool> &availability, const ::QtOpenAPI::OptionalParam<QList<QString>> &visits, const ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>> &mapfield, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postUrlEncodedFields, (const ::QtOpenAPI::OptionalParam<QString> &name = ::QtOpenAPI::OptionalParam<QString>(), const ::QtOpenAPI::OptionalParam<qint32> &status = ::QtOpenAPI::OptionalParam<qint32>(), const ::QtOpenAPI::OptionalParam<bool> &availability = ::QtOpenAPI::OptionalParam<bool>(), const ::QtOpenAPI::OptionalParam<QList<QString>> &visits = ::QtOpenAPI::OptionalParam<QList<QString>>(), const ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>> &mapfield = ::QtOpenAPI::OptionalParam<QMap<QString, QtOAIUser>>()), (name, status, availability, visits, mapfield), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postUrlEncodedNestedObject(const ::QtOpenAPI::OptionalParam<QtOAIUser> &user, const ::QtOpenAPI::OptionalParam<QString> &comment);
    * void postUrlEncodedNestedObject(const ::QtOpenAPI::OptionalParam<QtOAIUser> &user, const ::QtOpenAPI::OptionalParam<QString> &comment, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postUrlEncodedNestedObject, (const ::QtOpenAPI::OptionalParam<QtOAIUser> &user = ::QtOpenAPI::OptionalParam<QtOAIUser>(), const ::QtOpenAPI::OptionalParam<QString> &comment = ::QtOpenAPI::OptionalParam<QString>()), (user, comment), (const QString &), /* non-deprecated */)

    /**
    * \internal
    * The auto-generated API:
    * void postUrlEncodedObject(const ::QtOpenAPI::OptionalParam<QString> &name, const ::QtOpenAPI::OptionalParam<QString> &status, const ::QtOpenAPI::OptionalParam<qint32> &age);
    * void postUrlEncodedObject(const ::QtOpenAPI::OptionalParam<QString> &name, const ::QtOpenAPI::OptionalParam<QString> &status, const ::QtOpenAPI::OptionalParam<qint32> &age, QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_IMPL(postUrlEncodedObject, (const ::QtOpenAPI::OptionalParam<QString> &name = ::QtOpenAPI::OptionalParam<QString>(), const ::QtOpenAPI::OptionalParam<QString> &status = ::QtOpenAPI::OptionalParam<QString>(), const ::QtOpenAPI::OptionalParam<qint32> &age = ::QtOpenAPI::OptionalParam<qint32>()), (name, status, age), (const QString &), /* non-deprecated */)

Q_SIGNALS:
    /** Signal is emitted, if binaryType() request completed successfully. The \a summary contains a serialized server response. */
    void binaryTypeFinished(const QString &summary);
    /** Signal is emitted, if binaryType() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void binaryTypeErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonArray() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonArrayFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonArray() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonArrayErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonBool() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonBoolFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonBool() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonBoolErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonInt() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonIntFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonInt() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonIntErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonMap() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonMapFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonMap() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonMapErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonObject() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonObjectFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonObject() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonObjectErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonSeveralObjects() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonSeveralObjectsFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonSeveralObjects() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonSeveralObjectsErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postApplicationJsonString() request completed successfully. The \a summary contains a serialized server response. */
    void postApplicationJsonStringFinished(const QString &summary);
    /** Signal is emitted, if postApplicationJsonString() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postApplicationJsonStringErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postMultiPartData() request completed successfully. The \a summary contains a serialized server response. */
    void postMultiPartDataFinished(const QString &summary);
    /** Signal is emitted, if postMultiPartData() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postMultiPartDataErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postPlainTextType() request completed successfully. The \a summary contains a serialized server response. */
    void postPlainTextTypeFinished(const QString &summary);
    /** Signal is emitted, if postPlainTextType() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postPlainTextTypeErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postUrlEncodedFields() request completed successfully. The \a summary contains a serialized server response. */
    void postUrlEncodedFieldsFinished(const QString &summary);
    /** Signal is emitted, if postUrlEncodedFields() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postUrlEncodedFieldsErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postUrlEncodedNestedObject() request completed successfully. The \a summary contains a serialized server response. */
    void postUrlEncodedNestedObjectFinished(const QString &summary);
    /** Signal is emitted, if postUrlEncodedNestedObject() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postUrlEncodedNestedObjectErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);
    /** Signal is emitted, if postUrlEncodedObject() request completed successfully. The \a summary contains a serialized server response. */
    void postUrlEncodedObjectFinished(const QString &summary);
    /** Signal is emitted, if postUrlEncodedObject() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void postUrlEncodedObjectErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);

protected:
    QString m_testOperationPath;
    QByteArray m_requestContent;
};

} // namespace QtOpenAPI
#endif
