/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QtOAIPostMultiPartData_request_formObject.h
 *
 * 
 */

#ifndef QtOAIPostMultiPartData_request_formObject_H
#define QtOAIPostMultiPartData_request_formObject_H

#include "QtOAIObject.h"

#include <QString>

namespace QtOpenAPI {

class QtOAIPostMultiPartData_request_formObject : public QtOAIObject {
    Q_GADGET

    Q_PROPERTY(qint32 getObjectId READ getObjectId WRITE setObjectId)
    Q_PROPERTY(QString getObjectName READ getObjectName WRITE setObjectName)
public:
    QtOAIPostMultiPartData_request_formObject();
    QtOAIPostMultiPartData_request_formObject(const QString &json);
    ~QtOAIPostMultiPartData_request_formObject() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(const QJsonObject &json) override;
    void fromJson(const QString &jsonString) override;

    qint32 getObjectId() const;
    void setObjectId(const qint32 &objectId);
    bool isObjectIdSet() const;
    bool isObjectIdValid() const;

    QString getObjectName() const;
    void setObjectName(const QString &objectName);
    bool isObjectNameSet() const;
    bool isObjectNameValid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_objectId;
    bool m_objectIdIsSet;
    bool m_objectIdIsValid;

    QString m_objectName;
    bool m_objectNameIsSet;
    bool m_objectNameIsValid;
};

} // namespace QtOpenAPI

Q_DECLARE_METATYPE(QtOpenAPI::QtOAIPostMultiPartData_request_formObject)

#endif // QtOAIPostMultiPartData_request_formObject_H
