/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QtOAIUser.h"
#include "QtOAIHelpers.h"

#include <QtCore/qdebug.h>

namespace QtOpenAPI {

QtOAIUser::QtOAIUser(const QString &json)
{
    this->initializeModel();
    this->fromJson(json);
}

QtOAIUser::QtOAIUser()
{
    this->initializeModel();
}

QtOAIUser::~QtOAIUser()
{
}

void QtOAIUser::initializeModel()
{

    m_nameIsSet = false;
    m_nameIsValid = false;

    m_statusIsSet = false;
    m_statusIsValid = false;

    m_ageIsSet = false;
    m_ageIsValid = false;
}

void QtOAIUser::fromJson(const QString &jsonString)
{
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void QtOAIUser::fromJsonObject(const QJsonObject &json)
{

    m_nameIsValid = ::QtOpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_nameIsSet = !json[QString("name")].isNull() && m_nameIsValid;

    m_statusIsValid = ::QtOpenAPI::fromJsonValue(m_status, json[QString("status")]);
    m_statusIsSet = !json[QString("status")].isNull() && m_statusIsValid;

    m_ageIsValid = ::QtOpenAPI::fromJsonValue(m_age, json[QString("age")]);
    m_ageIsSet = !json[QString("age")].isNull() && m_ageIsValid;
}

QString QtOAIUser::asJson() const
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson(QJsonDocument::Compact);
    return QString(bytes);
}

QJsonObject QtOAIUser::asJsonObject() const
{
    QJsonObject obj;
    if (m_nameIsSet) {
        obj.insert(QString("name"), ::QtOpenAPI::toJsonValue(m_name));
    }
    if (m_statusIsSet) {
        obj.insert(QString("status"), ::QtOpenAPI::toJsonValue(m_status));
    }
    if (m_ageIsSet) {
        obj.insert(QString("age"), ::QtOpenAPI::toJsonValue(m_age));
    }
    return obj;
}

QString QtOAIUser::getName() const
{
    return m_name;
}
void QtOAIUser::setName(const QString &name)
{
    m_name = name;
    m_nameIsSet = true;
}

bool QtOAIUser::isNameSet() const
{
    return m_nameIsSet;
}

bool QtOAIUser::isNameValid() const
{
    return m_nameIsValid;
}

QString QtOAIUser::getStatus() const
{
    return m_status;
}
void QtOAIUser::setStatus(const QString &status)
{
    m_status = status;
    m_statusIsSet = true;
}

bool QtOAIUser::isStatusSet() const
{
    return m_statusIsSet;
}

bool QtOAIUser::isStatusValid() const
{
    return m_statusIsValid;
}

qint32 QtOAIUser::getAge() const
{
    return m_age;
}
void QtOAIUser::setAge(const qint32 &age)
{
    m_age = age;
    m_ageIsSet = true;
}

bool QtOAIUser::isAgeSet() const
{
    return m_ageIsSet;
}

bool QtOAIUser::isAgeValid() const
{
    return m_ageIsValid;
}

bool QtOAIUser::isSet() const
{
    bool isObjectUpdated = false;
    do {
        if (m_nameIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_statusIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_ageIsSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool QtOAIUser::isValid() const
{
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace QtOpenAPI
