/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QtOAIPostApplicationJsonSeveralObjects_request.h
 *
 * 
 */

#ifndef QtOAIPostApplicationJsonSeveralObjects_request_H
#define QtOAIPostApplicationJsonSeveralObjects_request_H

#include "QtOAIExports.h"
#include "QtOAIObject.h"

#include "QtOAIUser.h"
#include <QString>

namespace QtOpenAPI {

class QtOAI_EXPORT QtOAIPostApplicationJsonSeveralObjects_request : public QtOAIObject {
    Q_GADGET

    Q_PROPERTY(QString getUuid READ getUuid WRITE setUuid)
    Q_PROPERTY(QtOAIUser getUser READ getUser WRITE setUser)
public:
    QtOAIPostApplicationJsonSeveralObjects_request();
    QtOAIPostApplicationJsonSeveralObjects_request(const QString &json);
    ~QtOAIPostApplicationJsonSeveralObjects_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(const QJsonObject &json) override;
    void fromJson(const QString &jsonString) override;

    QString getUuid() const;
    void setUuid(const QString &uuid);
    bool isUuidSet() const;
    bool isUuidValid() const;

    QtOAIUser getUser() const;
    void setUser(const QtOAIUser &user);
    bool isUserSet() const;
    bool isUserValid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_uuid;
    bool m_uuidIsSet;
    bool m_uuidIsValid;

    QtOAIUser m_user;
    bool m_userIsSet;
    bool m_userIsValid;
};

} // namespace QtOpenAPI

Q_DECLARE_METATYPE(QtOpenAPI::QtOAIPostApplicationJsonSeveralObjects_request)

#endif // QtOAIPostApplicationJsonSeveralObjects_request_H
