/**
 * Qt Quick Demo - RESTful API client
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIColorPage.h"
#include "OAIHelpers.h"

#include <QtCore/qdebug.h>

namespace OpenAPI {

OAIColorPage::OAIColorPage(const QString &json)
{
    this->initializeModel();
    this->fromJson(json);
}

OAIColorPage::OAIColorPage()
{
    this->initializeModel();
}

OAIColorPage::~OAIColorPage()
{
}

void OAIColorPage::initializeModel()
{

    m_pageIsSet = false;
    m_pageIsValid = false;

    m_perPageIsSet = false;
    m_perPageIsValid = false;

    m_totalIsSet = false;
    m_totalIsValid = false;

    m_totalPagesIsSet = false;
    m_totalPagesIsValid = false;

    m_dataIsSet = false;
    m_dataIsValid = false;
}

void OAIColorPage::fromJson(const QString &jsonString)
{
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIColorPage::fromJsonObject(const QJsonObject &json)
{

    m_pageIsValid = ::OpenAPI::fromJsonValue(m_page, json[QString("page")]);
    m_pageIsSet = !json[QString("page")].isNull() && m_pageIsValid;

    m_perPageIsValid = ::OpenAPI::fromJsonValue(m_perPage, json[QString("per_page")]);
    m_perPageIsSet = !json[QString("per_page")].isNull() && m_perPageIsValid;

    m_totalIsValid = ::OpenAPI::fromJsonValue(m_total, json[QString("total")]);
    m_totalIsSet = !json[QString("total")].isNull() && m_totalIsValid;

    m_totalPagesIsValid = ::OpenAPI::fromJsonValue(m_totalPages, json[QString("total_pages")]);
    m_totalPagesIsSet = !json[QString("total_pages")].isNull() && m_totalPagesIsValid;

    m_dataIsValid = ::OpenAPI::fromJsonValue(m_data, json[QString("data")]);
    m_dataIsSet = !json[QString("data")].isNull() && m_dataIsValid;
}

QString OAIColorPage::asJson() const
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson(QJsonDocument::Compact);
    return QString(bytes);
}

QJsonObject OAIColorPage::asJsonObject() const
{
    QJsonObject obj;
    if (m_pageIsSet) {
        obj.insert(QString("page"), ::OpenAPI::toJsonValue(m_page));
    }
    if (m_perPageIsSet) {
        obj.insert(QString("per_page"), ::OpenAPI::toJsonValue(m_perPage));
    }
    if (m_totalIsSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(m_total));
    }
    if (m_totalPagesIsSet) {
        obj.insert(QString("total_pages"), ::OpenAPI::toJsonValue(m_totalPages));
    }
    if (m_data.size() > 0) {
        obj.insert(QString("data"), ::OpenAPI::toJsonValue(m_data));
    }
    return obj;
}

qint32 OAIColorPage::getPage() const
{
    return m_page;
}
void OAIColorPage::setPage(const qint32 &page)
{
    m_page = page;
    m_pageIsSet = true;
}

bool OAIColorPage::isPageSet() const
{
    return m_pageIsSet;
}

bool OAIColorPage::isPageValid() const
{
    return m_pageIsValid;
}

qint32 OAIColorPage::getPerPage() const
{
    return m_perPage;
}
void OAIColorPage::setPerPage(const qint32 &perPage)
{
    m_perPage = perPage;
    m_perPageIsSet = true;
}

bool OAIColorPage::isPerPageSet() const
{
    return m_perPageIsSet;
}

bool OAIColorPage::isPerPageValid() const
{
    return m_perPageIsValid;
}

qint32 OAIColorPage::getTotal() const
{
    return m_total;
}
void OAIColorPage::setTotal(const qint32 &total)
{
    m_total = total;
    m_totalIsSet = true;
}

bool OAIColorPage::isTotalSet() const
{
    return m_totalIsSet;
}

bool OAIColorPage::isTotalValid() const
{
    return m_totalIsValid;
}

qint32 OAIColorPage::getTotalPages() const
{
    return m_totalPages;
}
void OAIColorPage::setTotalPages(const qint32 &totalPages)
{
    m_totalPages = totalPages;
    m_totalPagesIsSet = true;
}

bool OAIColorPage::isTotalPagesSet() const
{
    return m_totalPagesIsSet;
}

bool OAIColorPage::isTotalPagesValid() const
{
    return m_totalPagesIsValid;
}

QList<OAIColor> OAIColorPage::getData() const
{
    return m_data;
}
void OAIColorPage::setData(const QList<OAIColor> &data)
{
    m_data = data;
    m_dataIsSet = true;
}

bool OAIColorPage::isDataSet() const
{
    return m_dataIsSet;
}

bool OAIColorPage::isDataValid() const
{
    return m_dataIsValid;
}

bool OAIColorPage::isSet() const
{
    bool isObjectUpdated = false;
    do {
        if (m_pageIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_perPageIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_totalIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_totalPagesIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_data.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIColorPage::isValid() const
{
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
