/**
 * OpenAPI Petstore
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_EXPORTS_H
#define OAI_EXPORTS_H

#include <QtCore/qtconfigmacros.h>

#if defined(OAI_LIB_SHARED) || !defined(OAI_LIB_STATIC)
#  if defined(OAI_BUILD_LIB)
#    define OAI_EXPORT Q_DECL_EXPORT
#  else
#    define OAI_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define OAI_EXPORT
#endif

#endif // OAI_EXPORTS_H
