/**
 * Qt Quick Demo - RESTful API client
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef QtOAI_QtOAIDefaultApi_H
#define QtOAI_QtOAIDefaultApi_H

#include "QtOAIBaseApi.h"
#include <QtNetwork/qrestreply.h>

#include "QtOAITestObject.h"
#include "QtOAITestOperation_request.h"
#include <QString>

namespace QtOpenAPI {

class QtOAIDefaultApi : public QtOAIBaseApi {
    Q_OBJECT
public:
    QtOAIDefaultApi() : QtOAIDefaultApi(nullptr) {}
    explicit QtOAIDefaultApi(QObject *parent);
    ~QtOAIDefaultApi() override;

    void initializeServerConfigs();
public:
    /**
    * \internal
    * The auto-generated API:
    * void testOperation(const qint32 &pathParam, const ::QtOpenAPI::OptionalParam<bool> &queryParam0, const ::QtOpenAPI::OptionalParam<QtOAITestObject> &queryParam1, const ::QtOpenAPI::OptionalParam<QList<qint32>> &queryParam2, const ::QtOpenAPI::OptionalParam<QtOAITestOperation_request> &qtOAITestOperationRequest);
    * void testOperation(const qint32 &pathParam, const ::QtOpenAPI::OptionalParam<bool> &queryParam0, const ::QtOpenAPI::OptionalParam<QtOAITestObject> &queryParam1, const ::QtOpenAPI::OptionalParam<QList<qint32>> &queryParam2, const ::QtOpenAPI::OptionalParam<QtOAITestOperation_request> &qtOAITestOperationRequest, QObject *object, [&](const QRestReply &reply){});
    * \endinternal
    */
    QtOAI_ADD_OPERATION_WITH_NO_RESPONSE_IMPL(testOperation, (const qint32 &pathParam, const ::QtOpenAPI::OptionalParam<bool> &queryParam0 = ::QtOpenAPI::OptionalParam<bool>(), const ::QtOpenAPI::OptionalParam<QtOAITestObject> &queryParam1 = ::QtOpenAPI::OptionalParam<QtOAITestObject>(), const ::QtOpenAPI::OptionalParam<QList<qint32>> &queryParam2 = ::QtOpenAPI::OptionalParam<QList<qint32>>(), const ::QtOpenAPI::OptionalParam<QtOAITestOperation_request> &qtOAITestOperationRequest = ::QtOpenAPI::OptionalParam<QtOAITestOperation_request>()), (pathParam, queryParam0, queryParam1, queryParam2, qtOAITestOperationRequest), /* non-deprecated */)

Q_SIGNALS:
    /** Signal is emitted, if testOperation() request completed successfully. */
    void testOperationFinished();
    /** Signal is emitted, if testOperation() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void testOperationErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);

protected:
    QString m_testOperationPath;
    QByteArray m_requestContent;
};

} // namespace QtOpenAPI
#endif
