/**
 * Qt Quick Demo - RESTful API client
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QtOAIRegisterApi.h"
#include "QtOAIServerConfiguration.h"

#include <QtCore/qanystringview.h>
#include <QtCore/qjsonarray.h>
#include <QtCore/qjsondocument.h>
#include <QtNetwork/qhttpmultipart.h>
#include <QtNetwork/qnetworkaccessmanager.h>
#include <QtNetwork/qnetworkreply.h>
#include <QtNetwork/qnetworkrequestfactory.h>
#include <QtNetwork/qrestaccessmanager.h>

using namespace Qt::StringLiterals;

namespace QtOpenAPI {

QtOAIRegisterApi::QtOAIRegisterApi(QObject *parent)
    : QtOAIBaseApi(parent)
{
    initializeServerConfigs();
}

QtOAIRegisterApi::~QtOAIRegisterApi()
{
}

void QtOAIRegisterApi::initializeServerConfigs()
{
    //Default server
    QList<QtOAIServerConfiguration> defaultConf = QList<QtOAIServerConfiguration>();
    //varying endpoint server
    defaultConf.append(QtOAIServerConfiguration(
    QUrl("https://reqres.in/api"),
    "Public REST API test service",
    QMap<QString, QtOAIServerVariable>()));
    defaultConf.append(QtOAIServerConfiguration(
    QUrl("http://127.0.0.1:49425/api"),
    "Qt-based REST API server",
    QMap<QString, QtOAIServerVariable>()));
    m_serverConfigs.insert("registerPost", defaultConf);
    m_serverIndices.insert("registerPost", 0);
}

/**
* \fn virtual void QtOAIRegisterApi::registerPost(const ::QtOpenAPI::OptionalParam<QtOAITestOperation_request> &qtOAITestOperationRequest = ::QtOpenAPI::OptionalParam<QtOAITestOperation_request>())
* 'registerPost' operation sends the request to a server.
* The request parameters are defined by a specification file.

* @param[in] qtOAITestOperationRequest QtOAITestOperation_request [optional]
*/

/**
* \fn template < Functor, > void QtOAIRegisterApi::registerPost(const ::QtOpenAPI::OptionalParam<QtOAITestOperation_request> &qtOAITestOperationRequest = ::QtOpenAPI::OptionalParam<QtOAITestOperation_request>(), const ContextTypeForFunctor< Functor > *context = nullptr, Functor &&callback = (){})
* 'registerPost' operation sends the request to a server.
* The request parameters are defined by a specification file.
*
* \attention Use the operation with following parameters in the callback:
* \code {c++}
*    registerPost(qtOAITestOperationRequest, this, [&](const QRestReply &reply) { if (reply.isSuccess()) ... });
* \endcode
* \note The template function can not be virtual in C++17.
* If you want to use 'makeOperationsVirtual' option for mocking API,
* please override virtual registerPostWithDataImpl() in derived class.
* The virtual registerPostWithDataImpl() is being called by the template
* function.

* @param[in] qtOAITestOperationRequest QtOAITestOperation_request [optional]
* @param[in] context const ContextTypeForFunctor< Functor > * [optional]
* @param[in] callback Functor && [optional]
*/

/**
* \fn void QtOAIRegisterApi::registerPostCallback(const QRestReply &reply)
* Processes a \a reply response from a server.
* The result of processed data is emitted by registerPostFinished() or
* being returned as a callback parameter of registerPost() request.
* @param[in] reply const QRestReply &
*/

/**
* \fn virtual void QtOAIRegisterApi::registerPostWithDataImpl(const ::QtOpenAPI::OptionalParam<QtOAITestOperation_request> &qtOAITestOperationRequest, const QObject *context, QtPrivate::QSlotObjectBase *slot)
* Implements the registerPost() operation request.
* \note If 'makeOperationsVirtual' option is true, this function is declared as virtual
* and can be overloaded for mocking registerPost() operation calls.

* @param[in] qtOAITestOperationRequest QtOAITestOperation_request [optional]
* @param[in] context const QObject * [optional]
* @param[in] slot QtPrivate::QSlotObjectBase * [optional]
*/
void QtOAIRegisterApi::registerPostWithDataImpl(const ::QtOpenAPI::OptionalParam<QtOAITestOperation_request> &qtOAITestOperationRequest, const QObject *context, QtPrivate::QSlotObjectBase *slot)
{
    const QUrl serverUrl = m_serverConfigs["registerPost"][m_serverIndices.value("registerPost")].serverUrl();
    QString fullPath = "/register";
    m_networkFactory->setBaseUrl(serverUrl);

    // set m_testOperationPath for serialization tests
    m_testOperationPath = fullPath;
    QtOAIHttpRequestInput input(fullPath, "POST");
    input.m_headers.replaceOrAppend(QHttpHeaders::WellKnownHeader::ContentType, "application/json"_L1);
    if (qtOAITestOperationRequest.hasValue()) {
        QByteArray output = qtOAITestOperationRequest.value().asJson().toUtf8();
        input.m_requestBody.append(output);
    } else if (qtOAITestOperationRequest.isNull()) {
        input.m_requestBody.append("null");
    }
    QNetworkRequest request
        = QtOAIHttpRequestWorker::getNetworkRequest(input, m_requestContent, m_networkFactory,
                                                  m_isResponseCompressionEnabled, m_isRequestCompressionEnabled);
    QNetworkReply *reply = execute(input, request, m_requestContent);
    if (reply != nullptr) {
        reply->setParent(this);
        m_callerData.insert(reply, QtOAICallerInfo{context, slot});
        connect(reply, &QNetworkReply::finished, this, [this, reply] {
            registerPostCallback(QRestReply(reply));
        });
        connect(reply, &QNetworkReply::errorOccurred, this, [this, reply] {
            if (reply) {
                emit registerPostErrorOccurred(reply->error(), reply->errorString());
                QtOAICallerInfo callerInfo = m_callerData.take(reply);
                if (callerInfo.slot) {
                    QRestReply restRepl(reply);
                    void *argv[] = { nullptr, &restRepl };
                    QObject *context = callerInfo.contextObject ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
                    callerInfo.slot->call(context, argv);
                }
            }
        });
    }
}

void QtOAIRegisterApi::registerPostCallback(const QRestReply &reply)
{
    auto netReply = reply.networkReply();
    if (netReply)
        netReply->disconnect(this);
    if (!reply.isSuccess())
        return;

    // Check if callback is provided
    QtOAICallerInfo callerInfo = m_callerData.take(netReply);
    if (callerInfo.slot) {
        void *argv[] = { nullptr, const_cast<QRestReply*>(&reply) };
        QObject *context = callerInfo.contextObject
                        ? const_cast<QObject*>(callerInfo.contextObject) : nullptr;
        callerInfo.slot->call(context, argv);
    }
    emit registerPostFinished();
}

} // namespace QtOpenAPI
