/**
 * Qt Quick Demo - RESTful API client
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QtOAIUserPage.h
 *
 * 
 */

#ifndef QtOAIUserPage_H
#define QtOAIUserPage_H

#include "QtOAIObject.h"

#include "QtOAIUser.h"
#include <QList>

namespace QtOpenAPI {
class QtOAIUser;

class QtOAIUserPage : public QtOAIObject {
    Q_GADGET

    Q_PROPERTY(qint32 getPage READ getPage WRITE setPage)
    Q_PROPERTY(qint32 getPerPage READ getPerPage WRITE setPerPage)
    Q_PROPERTY(qint32 getTotal READ getTotal WRITE setTotal)
    Q_PROPERTY(qint32 getTotalPages READ getTotalPages WRITE setTotalPages)
    Q_PROPERTY(QList<QtOAIUser> getData READ getData WRITE setData)
public:
    QtOAIUserPage();
    QtOAIUserPage(const QString &json);
    ~QtOAIUserPage() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(const QJsonObject &json) override;
    void fromJson(const QString &jsonString) override;

    qint32 getPage() const;
    void setPage(const qint32 &page);
    bool isPageSet() const;
    bool isPageValid() const;

    qint32 getPerPage() const;
    void setPerPage(const qint32 &perPage);
    bool isPerPageSet() const;
    bool isPerPageValid() const;

    qint32 getTotal() const;
    void setTotal(const qint32 &total);
    bool isTotalSet() const;
    bool isTotalValid() const;

    qint32 getTotalPages() const;
    void setTotalPages(const qint32 &totalPages);
    bool isTotalPagesSet() const;
    bool isTotalPagesValid() const;

    QList<QtOAIUser> getData() const;
    void setData(const QList<QtOAIUser> &data);
    bool isDataSet() const;
    bool isDataValid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_page;
    bool m_pageIsSet;
    bool m_pageIsValid;

    qint32 m_perPage;
    bool m_perPageIsSet;
    bool m_perPageIsValid;

    qint32 m_total;
    bool m_totalIsSet;
    bool m_totalIsValid;

    qint32 m_totalPages;
    bool m_totalPagesIsSet;
    bool m_totalPagesIsValid;

    QList<QtOAIUser> m_data;
    bool m_dataIsSet;
    bool m_dataIsValid;
};

} // namespace QtOpenAPI

Q_DECLARE_METATYPE(QtOpenAPI::QtOAIUserPage)

#endif // QtOAIUserPage_H
