/**
 * Qt Quick Demo - RESTful API client
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QtOAITestOperation_request.h
 *
 * 
 */

#ifndef QtOAITestOperation_request_H
#define QtOAITestOperation_request_H

#include "QtOAIObject.h"

#include <QString>

namespace QtOpenAPI {

class QtOAITestOperation_request : public QtOAIObject {
    Q_GADGET

    Q_PROPERTY(QString getEmail READ getEmail WRITE setEmail)
    Q_PROPERTY(QString getPassword READ getPassword WRITE setPassword)
public:
    QtOAITestOperation_request();
    QtOAITestOperation_request(const QString &json);
    ~QtOAITestOperation_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(const QJsonObject &json) override;
    void fromJson(const QString &jsonString) override;

    QString getEmail() const;
    void setEmail(const QString &email);
    bool isEmailSet() const;
    bool isEmailValid() const;

    QString getPassword() const;
    void setPassword(const QString &password);
    bool isPasswordSet() const;
    bool isPasswordValid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_email;
    bool m_emailIsSet;
    bool m_emailIsValid;

    QString m_password;
    bool m_passwordIsSet;
    bool m_passwordIsValid;
};

} // namespace QtOpenAPI

Q_DECLARE_METATYPE(QtOpenAPI::QtOAITestOperation_request)

#endif // QtOAITestOperation_request_H
