/**
 * Qt Quick Demo - RESTful API client
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QtOAIColor.h"
#include "QtOAIHelpers.h"

#include <QtCore/qdebug.h>

namespace QtOpenAPI {

QtOAIColor::QtOAIColor(const QString &json)
{
    this->initializeModel();
    this->fromJson(json);
}

QtOAIColor::QtOAIColor()
{
    this->initializeModel();
}

QtOAIColor::~QtOAIColor()
{
}

void QtOAIColor::initializeModel()
{

    m_idIsSet = false;
    m_idIsValid = false;

    m_nameIsSet = false;
    m_nameIsValid = false;

    m_yearIsSet = false;
    m_yearIsValid = false;

    m_colorIsSet = false;
    m_colorIsValid = false;

    m_pantoneValueIsSet = false;
    m_pantoneValueIsValid = false;
}

void QtOAIColor::fromJson(const QString &jsonString)
{
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void QtOAIColor::fromJsonObject(const QJsonObject &json)
{

    m_idIsValid = ::QtOpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_idIsSet = !json[QString("id")].isNull() && m_idIsValid;

    m_nameIsValid = ::QtOpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_nameIsSet = !json[QString("name")].isNull() && m_nameIsValid;

    m_yearIsValid = ::QtOpenAPI::fromJsonValue(m_year, json[QString("year")]);
    m_yearIsSet = !json[QString("year")].isNull() && m_yearIsValid;

    m_colorIsValid = ::QtOpenAPI::fromJsonValue(m_color, json[QString("color")]);
    m_colorIsSet = !json[QString("color")].isNull() && m_colorIsValid;

    m_pantoneValueIsValid = ::QtOpenAPI::fromJsonValue(m_pantoneValue, json[QString("pantone_value")]);
    m_pantoneValueIsSet = !json[QString("pantone_value")].isNull() && m_pantoneValueIsValid;
}

QString QtOAIColor::asJson() const
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson(QJsonDocument::Compact);
    return QString(bytes);
}

QJsonObject QtOAIColor::asJsonObject() const
{
    QJsonObject obj;
    if (m_idIsSet) {
        obj.insert(QString("id"), ::QtOpenAPI::toJsonValue(m_id));
    }
    if (m_nameIsSet) {
        obj.insert(QString("name"), ::QtOpenAPI::toJsonValue(m_name));
    }
    if (m_yearIsSet) {
        obj.insert(QString("year"), ::QtOpenAPI::toJsonValue(m_year));
    }
    if (m_colorIsSet) {
        obj.insert(QString("color"), ::QtOpenAPI::toJsonValue(m_color));
    }
    if (m_pantoneValueIsSet) {
        obj.insert(QString("pantone_value"), ::QtOpenAPI::toJsonValue(m_pantoneValue));
    }
    return obj;
}

qint64 QtOAIColor::getId() const
{
    return m_id;
}
void QtOAIColor::setId(const qint64 &id)
{
    m_id = id;
    m_idIsSet = true;
}

bool QtOAIColor::isIdSet() const
{
    return m_idIsSet;
}

bool QtOAIColor::isIdValid() const
{
    return m_idIsValid;
}

QString QtOAIColor::getName() const
{
    return m_name;
}
void QtOAIColor::setName(const QString &name)
{
    m_name = name;
    m_nameIsSet = true;
}

bool QtOAIColor::isNameSet() const
{
    return m_nameIsSet;
}

bool QtOAIColor::isNameValid() const
{
    return m_nameIsValid;
}

qint32 QtOAIColor::getYear() const
{
    return m_year;
}
void QtOAIColor::setYear(const qint32 &year)
{
    m_year = year;
    m_yearIsSet = true;
}

bool QtOAIColor::isYearSet() const
{
    return m_yearIsSet;
}

bool QtOAIColor::isYearValid() const
{
    return m_yearIsValid;
}

QString QtOAIColor::getColor() const
{
    return m_color;
}
void QtOAIColor::setColor(const QString &color)
{
    m_color = color;
    m_colorIsSet = true;
}

bool QtOAIColor::isColorSet() const
{
    return m_colorIsSet;
}

bool QtOAIColor::isColorValid() const
{
    return m_colorIsValid;
}

QString QtOAIColor::getPantoneValue() const
{
    return m_pantoneValue;
}
void QtOAIColor::setPantoneValue(const QString &pantoneValue)
{
    m_pantoneValue = pantoneValue;
    m_pantoneValueIsSet = true;
}

bool QtOAIColor::isPantoneValueSet() const
{
    return m_pantoneValueIsSet;
}

bool QtOAIColor::isPantoneValueValid() const
{
    return m_pantoneValueIsValid;
}

bool QtOAIColor::isSet() const
{
    bool isObjectUpdated = false;
    do {
        if (m_idIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_nameIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_yearIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_colorIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_pantoneValueIsSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool QtOAIColor::isValid() const
{
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace QtOpenAPI
