/*
 * Simple nested data structures
 *
 * File tests straightforward nested-level array-of-array-of-array structures and deep nested reference structures.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Label3 struct {

	Data Label4 `json:"data,omitempty"`
}
