/**
 * Client with 'QtOpenAPICommon' option Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef QtOAI_EXPORTS_H
#define QtOAI_EXPORTS_H

#include <QtCore/qtconfigmacros.h>

#if defined(QtOAI_LIB_SHARED) || !defined(QtOAI_LIB_STATIC)
#  if defined(QtOAI_BUILD_LIB)
#    define QtOAI_EXPORT Q_DECL_EXPORT
#  else
#    define QtOAI_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define QtOAI_EXPORT
#endif

#endif // QtOAI_EXPORTS_H
