# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: Apache-2.0

openapi: 3.1.1
servers:
  - url: 'http://127.0.0.1:10209/v2'
info:
  title: Operation Parameters Test
  description: >
    This specification is intended for testing purposes. It demonstrates a wide range of content types for requestBody. The goal is to verify correct url for each case.
  version: 1.0.0
tags:
  - name: test
    description: test operations

paths:
  /reqBody/appjson/string/postApplicationJsonString:
    post:
      tags:
        - test
      summary: Get request-body, application-json, string
      operationId: postApplicationJsonString
      requestBody:
        content:
          application/json:
            schema:
              type: [string, 'null']
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/appjson/bool/postApplicationJsonBool:
    post:
      tags:
        - test
      summary: Post request-body, application-json, boolean
      operationId: postApplicationJsonBool
      requestBody:
        content:
          application/json:
            schema:
              type: boolean
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/appjson/integer/postApplicationJsonInt:
    post:
      tags:
        - test
      summary: Post request-body, application-json, integer
      operationId: postApplicationJsonInt
      requestBody:
        content:
          application/json:
            schema:
              type: integer
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/appjson/array/postApplicationJsonArray:
    post:
      tags:
        - test
      summary: Put request-body, application-json, array
      operationId: postApplicationJsonArray
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/appjson/object/postApplicationJsonMap:
    post:
      tags:
        - test
      summary: Post request-body, application-json, map of object
      operationId: postApplicationJsonMap
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/appjson/object/postApplicationJsonObject:
    post:
      tags:
        - test
      summary: Post request-body, application-json, object
      operationId: postApplicationJsonObject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/appjson/object/postApplicationJsonSeveralObjects:
    post:
      tags:
        - test
      summary: Post request-body, application-json, object
      operationId: postApplicationJsonSeveralObjects
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  uuid: # the unique user id
                    type: string
                    format: uuid
                  user:
                    type: object
                    $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/octetstream/binaryType:
    post:
      tags:
        - test
      summary: Test body parameter
      description: Test body parameter
      operationId: binaryType
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/string/postPlainTextType:
    post:
      tags:
        - test
      summary: Post a simple text, like a user input
      operationId: postPlainTextType
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/urlencoded/postUrlEncodedFields:
    post:
      tags:
        - test
      summary: post Url Encoded simple key-value pairs
      operationId: postUrlEncodedFields
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                # default for primitives without a special format is text/plain
                name:
                  type: string
                # default for primitives without a special format is text/plain
                status:
                  type: integer
                # default for primitives without a special format is text/plain
                availability:
                  type: boolean
                # default for array of strings without a special format is text/plain
                visits:
                  type: array
                  items:
                    type: string
                # default for a map is `application/json`
                mapfield:
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/urlencoded/postUrlEncodedNestedObject:
    post:
      tags:
        - test
      summary: post Url Encoded simple key-value pairs
      operationId: postUrlEncodedNestedObject
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                # default for object is application/json
                user:
                  type: object
                  $ref: '#/components/schemas/User'
                # default for primitives without a special format is text/plain
                comment:
                  type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /reqBody/urlencoded/postUrlEncodedObject:
    post:
      tags:
        - test
      summary: post Url Encoded simple key-value pairs
      operationId: postUrlEncodedObject
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              # default for object is application/json
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    User:
      properties:
        name:
          description: User name
          type: string
        status:
          description: User status
          type: string
        age:
          description: User age
          type: integer
          format: int32
