/**
 * OpenAPI Generated Petstore Client
 *
 * This is a sample of Petstore application.
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * apiresponse.h
 *
 * Describes the result of uploading an image resource
 */

#ifndef APIRESPONSE_H
#define APIRESPONSE_H

#include "cmakegeneratedclientexports.h"
#include "qoaiobject.h"


#include <QString>

namespace QtOpenAPI {

class CMAKEGENERATEDCLIENT_EXPORT ApiResponse : public QtOpenApiCommon::QOAIObject {
    Q_GADGET

    Q_PROPERTY(qint32 code READ getCode WRITE setCode)
    Q_PROPERTY(QString type READ getType WRITE setType)
    Q_PROPERTY(QString message READ getMessage WRITE setMessage)
public:
    ApiResponse();
    Q_IMPLICIT ApiResponse(const QString &json);
    ~ApiResponse() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(const QJsonValue &json) override;
    void fromJson(const QString &jsonString) override;

    qint32 getCode() const;
    void setCode(const qint32 &code);
    bool isCodeValueSet() const;
    bool isCodeValueValid() const;

    QString getType() const;
    void setType(const QString &type);
    bool isTypeValueSet() const;
    bool isTypeValueValid() const;

    QString getMessage() const;
    void setMessage(const QString &message);
    bool isMessageValueSet() const;
    bool isMessageValueValid() const;

    bool isSet() const override;
    bool isValid() const override;

private:
    void initializeModel();
    qint32 m_code;
    bool m_codeIsSet;
    bool m_codeIsValid;
    QString m_type;
    bool m_typeIsSet;
    bool m_typeIsValid;
    QString m_message;
    bool m_messageIsSet;
    bool m_messageIsValid;
};

} // namespace QtOpenAPI

Q_DECLARE_METATYPE(QtOpenAPI::ApiResponse)

#endif // APIRESPONSE_H
