/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QtOAIFloatResponse.h
 *
 * 
 */

#ifndef QtOAIFloatResponse_H
#define QtOAIFloatResponse_H

#include "QtOAIObject.h"

#include <QString>

namespace QtOpenAPI {

class QtOAIFloatResponse : public QtOAIObject {
    Q_GADGET

    Q_PROPERTY(QString getStringValue READ getStringValue WRITE setStringValue)
    Q_PROPERTY(float getValue READ getValue WRITE setValue)
public:
    QtOAIFloatResponse();
    QtOAIFloatResponse(const QString &json);
    ~QtOAIFloatResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(const QJsonObject &json) override;
    void fromJson(const QString &jsonString) override;

    QString getStringValue() const;
    void setStringValue(const QString &stringValue);
    bool isStringValueSet() const;
    bool isStringValueValid() const;

    float getValue() const;
    void setValue(const float &value);
    bool isValueSet() const;
    bool isValueValid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_stringValue;
    bool m_stringValueIsSet;
    bool m_stringValueIsValid;

    float m_value;
    bool m_valueIsSet;
    bool m_valueIsValid;
};

} // namespace QtOpenAPI

Q_DECLARE_METATYPE(QtOpenAPI::QtOAIFloatResponse)

#endif // QtOAIFloatResponse_H
