/**
 * Operation Parameters Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QtOAIFloatResponse.h"
#include "QtOAIHelpers.h"

#include <QtCore/qdebug.h>

namespace QtOpenAPI {

QtOAIFloatResponse::QtOAIFloatResponse(const QString &json)
{
    this->initializeModel();
    this->fromJson(json);
}

QtOAIFloatResponse::QtOAIFloatResponse()
{
    this->initializeModel();
}

QtOAIFloatResponse::~QtOAIFloatResponse()
{
}

void QtOAIFloatResponse::initializeModel()
{

    m_stringValueIsSet = false;
    m_stringValueIsValid = false;

    m_valueIsSet = false;
    m_valueIsValid = false;
}

void QtOAIFloatResponse::fromJson(const QString &jsonString)
{
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void QtOAIFloatResponse::fromJsonObject(const QJsonObject &json)
{

    m_stringValueIsValid = ::QtOpenAPI::fromJsonValue(m_stringValue, json[QString("stringValue")]);
    m_stringValueIsSet = !json[QString("stringValue")].isNull() && m_stringValueIsValid;

    m_valueIsValid = ::QtOpenAPI::fromJsonValue(m_value, json[QString("value")]);
    m_valueIsSet = !json[QString("value")].isNull() && m_valueIsValid;
}

QString QtOAIFloatResponse::asJson() const
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson(QJsonDocument::Compact);
    return QString(bytes);
}

QJsonObject QtOAIFloatResponse::asJsonObject() const
{
    QJsonObject obj;
    if (m_stringValueIsSet) {
        obj.insert(QString("stringValue"), ::QtOpenAPI::toJsonValue(m_stringValue));
    }
    if (m_valueIsSet) {
        obj.insert(QString("value"), ::QtOpenAPI::toJsonValue(m_value));
    }
    return obj;
}

QString QtOAIFloatResponse::getStringValue() const
{
    return m_stringValue;
}
void QtOAIFloatResponse::setStringValue(const QString &stringValue)
{
    m_stringValue = stringValue;
    m_stringValueIsSet = true;
}

bool QtOAIFloatResponse::isStringValueSet() const
{
    return m_stringValueIsSet;
}

bool QtOAIFloatResponse::isStringValueValid() const
{
    return m_stringValueIsValid;
}

float QtOAIFloatResponse::getValue() const
{
    return m_value;
}
void QtOAIFloatResponse::setValue(const float &value)
{
    m_value = value;
    m_valueIsSet = true;
}

bool QtOAIFloatResponse::isValueSet() const
{
    return m_valueIsSet;
}

bool QtOAIFloatResponse::isValueValid() const
{
    return m_valueIsValid;
}

bool QtOAIFloatResponse::isSet() const
{
    bool isObjectUpdated = false;
    do {
        if (m_stringValueIsSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_valueIsSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool QtOAIFloatResponse::isValid() const
{
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace QtOpenAPI
