/*
 * Operation Parameters Test
 *
 * This specification is intended for testing purposes. It demonstrates a wide range of combinations of the `style` and `explode` attributes for parameters in various locations: query, path, header, and cookie. The goal is to verify correct path and parameter generation for each case.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TestObject struct {

	// Updated name
	Name string `json:"name,omitempty"`

	// Updated status
	Status string `json:"status,omitempty"`

	// age number
	Age int32 `json:"age,omitempty"`
}
