/**
 * OpenAPI Petstore
 * This is a sample of Petstore application. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIPetApiHandler_H
#define OAI_OAIPetApiHandler_H

#include <QObject>

#include "OAIApiResponse.h"
#include "OAIHttpFileElement.h"
#include "OAIPet.h"
#include <QList>
#include <QMap>
#include <QString>

namespace OpenAPI {

class OAIPetApiHandler : public QObject
{
    Q_OBJECT

public:
    OAIPetApiHandler();
    virtual ~OAIPetApiHandler();


public Q_SLOTS:
    virtual void addPet(OAIPet body, bool passed);
    virtual void deletePet(qint64 pet_id, QString api_key, bool passed);
    virtual void findPetsByAgeAndPatience(QList<qint32> pet_data);
    virtual void findPetsByStatus(QList<QString> status);
    virtual void findPetsByTags(QList<QString> tags);
    virtual void findPetsImageById(qint64 petId);
    virtual void getJsonFile(qint64 pet_id);
    virtual void getPetById(qint64 pet_id);
    virtual void updatePet(OAIPet body);
    virtual void updatePetWithForm(qint64 pet_id, QString name, QString status);
    virtual void uploadFile(qint64 pet_id, QString additional_metadata, OAIHttpFileElement file);

private:
    QMap<qint64, OAIPet> m_pets;
};

}

#endif // OAI_OAIPetApiHandler_H
