/**
 * Compression Test
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef QtOAI_QtOAITestApi_H
#define QtOAI_QtOAITestApi_H

#include "QtOAIBaseApi.h"
#include "QtOAIExports.h"
#include <QtNetwork/qrestreply.h>

#include <QString>

namespace QtOpenAPI {

class QtOAI_EXPORT QtOAITestApi : public QtOAIBaseApi {
    Q_OBJECT
public:
    QtOAITestApi() : QtOAITestApi(nullptr) {}
    explicit QtOAITestApi(QObject *parent);
    ~QtOAITestApi() override;

    void initializeServerConfigs();
public:
    /**
    * \internal
    * The auto-generated API:
    * void dummyOperation();
    * void dummyOperation(QObject *object, [&](const QRestReply &reply, const QString &summary){});
    * \endinternal
    */
    QtOAI_ADD_NO_PARAMS_OPERATION_WITH_RESPONSE_IMPL(dummyOperation, (const QString &), /* non-deprecated */)

Q_SIGNALS:
    /** Signal is emitted, if dummyOperation() request completed successfully. The \a summary contains a serialized server response. */
    void dummyOperationFinished(const QString &summary);
    /** Signal is emitted, if dummyOperation() request completed with an error. \a errorType and \a errorStr contain an information about the error. */
    void dummyOperationErrorOccurred(QNetworkReply::NetworkError errorType, const QString &errorStr);

protected:
    QString m_testOperationPath;
    QByteArray m_requestContent;
};

} // namespace QtOpenAPI
#endif
